packages/apps/crm/src/screens/catalog/CatalogListScreen.js, packages/apps/crm/src/screens/lead/LeadListScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderOperationListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ChildrenManufOrderListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductListScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js, packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js, packages/apps/stock/src/screens/inventories/InventoryListScreen.js, packages/apps/stock/src/screens/products/ProductStockLocationDetailsScreen.js, packages/apps/stock/src/screens/stockCorrections/StockCorrectionListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js, packages/core/src/components/templates/AttachedFilesView/AttachedFilesView.js, packages/core/src/utils/filter.ts, packages/core/src/utils/index.ts, packages/ui/src/components/organisms/ChipSelect/ChipSelect.tsx
=> Refactor : ChipSelect Component

packages/apps/crm/src/api/contact-api.js, packages/apps/crm/src/api/partner-api.js, packages/apps/crm/src/features/contactSlice.js, packages/apps/crm/src/features/partnerSlice.js, packages/apps/crm/src/i18n/en.json, packages/apps/crm/src/i18n/fr.json, packages/apps/crm/src/screens/contact/ContactDetailsScreen.js, packages/apps/crm/src/screens/contact/ContactFormScreen.js, packages/apps/crm/src/screens/contact/ContactListScreen.js, packages/apps/crm/src/screens/contact/index.js, packages/core/src/components/organisms/AutoCompleteSearchInput/AutoCompleteSearchInput.tsx
=> feat: add ContactFormScreen

packages/apps/crm/src/api/client-api.js, packages/apps/crm/src/features/clientSlice.js, packages/apps/crm/src/screens/client/ClientDetailsScreen.js, packages/apps/crm/src/screens/client/ClientFormScreen.js, packages/apps/crm/src/screens/client/index.js
=> feat: add ClientFormScreen

packages/apps/manufacturing/src/api/operation-order-api.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderPlanningScreen.js, packages/apps/manufacturing/src/types/operation-order.tsx, packages/core/src/components/external/PlanningView/PlanningView.tsx, packages/core/src/components/external/PlanningView/agenda.helpers.ts, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/utils/date.ts, packages/core/src/utils/formatters.ts, packages/core/src/utils/index.ts
=> feat: enable calendar multiday events

packages/apps/crm/src/api/event-api.js, packages/apps/crm/src/components/molecules/PlanningEventCard/PlanningEventCard.tsx, packages/apps/crm/src/components/molecules/index.js, packages/apps/crm/src/features/eventSlice.js, packages/apps/crm/src/index.ts, packages/apps/crm/src/screens/event/EventPlanningScreen.js, packages/apps/crm/src/screens/event/index.js, packages/apps/crm/src/types/event-type.ts
=> feat: add event planning screen

packages/apps/crm/src/api/event-api.js, packages/apps/crm/src/components/molecules/EventCard/EventCard.tsx, packages/apps/crm/src/components/molecules/PlanningEventCard/PlanningEventCard.tsx, packages/apps/crm/src/components/organisms/DropdownEventView/DropdownEventView.tsx, packages/apps/crm/src/features/eventSlice.js, packages/apps/crm/src/i18n/en.json, packages/apps/crm/src/i18n/fr.json, packages/apps/crm/src/screens/catalog/CatalogListScreen.js, packages/apps/crm/src/screens/client/ClientDetailsScreen.js, packages/apps/crm/src/screens/contact/ContactDetailsScreen.js, packages/apps/crm/src/screens/event/EventDetailsScreen.js, packages/apps/crm/src/screens/event/EventPlanningScreen.js, packages/apps/crm/src/screens/event/index.js, packages/apps/crm/src/screens/lead/LeadDetailsScreen.js, packages/apps/crm/src/screens/prospect/ProspectDetailsScreen.js, packages/apps/crm/src/types/event-type.ts
=> feat : add EventDetailsScreen

packages/core/src/api/mobile-config-api.ts, packages/core/src/app/ContextedApplication.tsx, packages/core/src/app/RootNavigator.js, packages/core/src/auth/screens/UserScreen.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/navigator/Navigator.js, packages/core/src/navigator/drawer/DrawerContent.js, packages/core/src/navigator/module.helper.js, packages/ui/src/components/molecules/IconButton/IconButton.tsx
=> fix: manage no apps enabled

packages/apps/stock/src/components/organisms/InternalMoveLineCard/InternalMoveLineCard.tsx, packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js, packages/core/src/screens/LoginScreen.js, yarn.lock
=> fix: manage screen position when keyboard is open

packages/core/src/components/molecules/InputBarCodeCard/InputBarCodeCard.js, packages/core/src/components/organisms/DateInput/DateInput.tsx, packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx, packages/ui/src/components/molecules/FormHtmlInput/FormHtmlInput.tsx, packages/ui/src/components/molecules/FormIncrementInput/FormIncrementInput.tsx, packages/ui/src/components/molecules/FormInput/FormInput.tsx, packages/ui/src/components/molecules/IconInput/IconInput.tsx, packages/ui/src/components/molecules/Increment/Increment.tsx, packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx, packages/ui/src/components/organisms/Picker/Picker.tsx, packages/ui/src/utils/commons-styles.js, packages/ui/src/utils/commons-utlis.ts
=> feat: add border color on input focus

packages/core/src/features/authSlice.js, packages/core/src/utils/api.ts
=> fix: manage url without http / https prefix

packages/core/src/components/molecules/HeaderOptionsMenuItem/HeaderOptionMenuItem.tsx, packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js, packages/ui/src/components/molecules/DropdownMenu/DropdownMenu.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/src/components/organisms/DropdownMenuItem/DropdownMenuItem.tsx, packages/ui/src/components/organisms/index.tsx
=> feat: hide header icon actions for small screen

packages/core/src/api/login-api.ts, packages/core/src/features/authSlice.js
=> fix: remove axios config on log out

packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js, packages/apps/stock/src/screens/inventories/InventoryListScreen.js, packages/apps/stock/src/screens/products/ProductListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js, packages/core/src/components/external/Scanner/Scanner.js, packages/core/src/components/molecules/InputBarCodeCard/InputBarCodeCard.js, packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx, packages/core/src/hooks/use-scan-activator.js, packages/core/src/screens/LoginScreen.js, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx, yarn.lock
=> fix: manage Zebra device issues

packages/apps/stock/src/components/organisms/ProductCardInfo/ProductCardInfo.tsx, packages/apps/stock/src/models/objectFields.ts, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryDetailScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveDetailsGeneralScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js, packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js, packages/apps/stock/src/screens/inventories/InventoryStartedDetailsScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalDetailsScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js, packages/apps/stock/src/utils/line-navigation.ts, packages/core/src/utils/string.ts, yarn.lock
=> fix: should not check product if tracking number is defined

packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx, packages/ui/src/components/organisms/SearchBar/SearchBar.tsx
=> feat: show first 5 items when user focus on the AutocompleteSearch

packages/core/src/features/authSlice.js, packages/core/src/utils/api.ts, packages/core/src/utils/formatters.ts
=> fix: remove unwanted regexes from the url

packages/core/src/auth/screens/SettingsScreen.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json
=> feat: display instance url to which user is connected

example/app.config.js, packages/apps/crm/src/api/client-api.js, packages/apps/crm/src/api/contact-api.js, packages/apps/crm/src/api/leads-api.js, packages/apps/crm/src/api/prospect-api.js, packages/apps/stock/src/api/supplychain-config-api.js, packages/core/src/api/mobile-config-api.ts, packages/core/src/app/Application.tsx, packages/core/src/app/ContextedApplication.tsx, packages/core/src/auth/api/config-api.js, packages/core/src/auth/screens/UserScreen.js, packages/core/src/config/RouterProvider.ts, packages/core/src/config/index.ts, packages/core/src/config/routes.js, packages/core/src/index.ts, packages/error/src/ErrorBoundary.tsx
=> fix: fix broken endpoints for aos v7

packages/apps/stock/src/api/index.ts, packages/apps/stock/src/api/internal-move-api.js, packages/apps/stock/src/api/internal-move-line-api.js, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryViewAllContainer/CustomerDeliveryViewAllContainer.js, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineButtons/InternalMoveLineButtons.js, packages/apps/stock/src/components/templates/internalMove/InternalMoveRealizeButton/InternalMoveRealizeButton.js, packages/apps/stock/src/components/templates/internalMove/InternalMoveViewAllContainer/InternalMoveViewAllContainer.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalViewAllContainer/SupplierArrivalViewAllContainer.js, packages/apps/stock/src/features/asyncFunctions-index.ts, packages/apps/stock/src/features/internalMoveLineSlice.js, packages/apps/stock/src/features/internalMoveSlice.js, packages/apps/stock/src/models/objectFields.ts, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
=> fix: manage isRealQtyModifiedByUser and use generic API request for internal move line

packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx, packages/apps/stock/src/i18n/en.json, packages/apps/stock/src/i18n/fr.json, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js, packages/core/src/utils/filter.ts, yarn.lock
=> feat: manage partially done stock move lines

packages/apps/manufacturing/src/components/organisms/LinkedManufacturingOrderCard/LinkedManufacturingOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/index.js, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListProductionOrderScreen.js, yarn.lock
=> feat: add copy to clipboard manufOrderSeq

packages/apps/crm/src/hooks/use-crm-header-actions.ts, packages/apps/manufacturing/src/hooks/use-manufacturing-headers.js, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js, packages/apps/stock/src/components/templates/inventory/InventoryButtons/InventoryButtons.js, packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionButtons/StockCorrectionButtons.js, packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionCreationButton/StockCorrectionCreationButton.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js, packages/apps/stock/src/hooks/use-stock-header-actions.js, packages/apps/stock/src/screens/stockCorrections/StockCorrectionDetailsScreen.js, packages/core/src/auth/api/config-api.js, packages/core/src/navigator/module.helper.ts, yarn.lock
=> feat: use new stock configs from mobile settings

example/app.config.js, packages/core/src/app/Application.tsx, packages/core/src/app/ContextsProvider.tsx, packages/ui/src/theme/ThemeContext.tsx, packages/ui/src/theme/WritingThemeContext.tsx, packages/ui/src/theme/theme-context.helper.ts, packages/ui/src/theme/writing-theme-context.helper.ts, packages/ui/src/utils/objects.ts
* add show modules subtitle to app config file
* add theme colors config to app config file
* add writing them config to app config file
RM#62562
=> feat: improve config file

packages/apps/crm/src/screens/catalog/CatalogListScreen.js, packages/apps/crm/src/screens/event/EventPlanningScreen.js, packages/apps/crm/src/screens/lead/LeadListScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/ui/src/components/molecules/MultiValuePickerButton/MultiValuePickerButton.tsx, packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx, packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
=> feat: replace status ChipSelect by MultiValuePicker for CRM screens

packages/core/src/auth/i18n/en.json, packages/core/src/auth/i18n/fr.json, packages/core/src/components/organisms/LogoImage/LogoImage.js, packages/core/src/components/organisms/SessionInput/SessionInput.js, packages/core/src/components/organisms/SessionNameInput/SessionNameInput.js, packages/core/src/components/organisms/UsernameInput/UsernameInput.js, packages/core/src/components/organisms/index.js, packages/core/src/components/templates/PopupCreateSession/PopupCreateSession.js, packages/core/src/components/templates/PopupSession/PopupSession.js, packages/core/src/components/templates/PopupSessionList/PopupSessionList.js, packages/core/src/components/templates/index.js, packages/core/src/screens/LoginScreen.js, packages/ui/src/components/molecules/InfoBubble/InfoBubble.tsx, yarn.lock
=> feat: improve display sessions

packages/core/src/features/authSlice.js, packages/core/src/screens/LoginScreen.js, packages/core/src/utils/storage-keys.tsx, yarn.lock
=> feat: save url in storage

example/app.config.js, packages/core/src/app/Application.tsx, packages/core/src/app/ContextedApplication.tsx, packages/core/src/app/ContextsProvider.tsx, packages/core/src/app/RootNavigator.js, packages/core/src/auth/i18n/en.json, packages/core/src/auth/i18n/fr.json, packages/core/src/auth/screens/SettingsScreen.js, packages/core/src/navigator/Navigator.js, packages/core/src/navigator/drawer/DrawerContent.js, packages/ui/src/config/ConfigContext.tsx, yarn.lock
=> feat:  manage drawer subtitles dynamically

.github/workflows/gradle.yml, .licenserc.json
=> chore: add check license job on pipeline

packages/core/src/api/login-api.ts, packages/core/src/app/ContextedApplication.tsx, packages/core/src/auth/hooks/use-auth-headers.js, packages/core/src/auth/i18n/en.json, packages/core/src/auth/i18n/fr.json, packages/core/src/auth/screens/UserScreen.js, packages/core/src/features/authSlice.js
=> feat: add banner on header when user is connected on test instance

packages/core/src/app/RootNavigator.js, packages/core/src/auth/hooks/use-auth-headers.js, packages/core/src/auth/screens/UserScreen.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json
=> feat: add banner on header when user is offline

packages/core/src/api/login-api.ts, packages/core/src/apiProviders/middlewares/index.ts, packages/core/src/apiProviders/middlewares/translation.ts, packages/core/src/features/authSlice.js, packages/core/src/utils/index.ts, packages/core/src/utils/object.ts
=> feat: manage translations on values fetched from AOS/AOP

packages/core/src/auth/screens/UserScreen.js, packages/ui/src/components/organisms/ProgressBar/ProgressBar.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/ProgressBar.stories.tsx, yarn.lock
=> feat: add progressbar component

packages/apps/helpdesk/src/api/ticket-api.js, packages/apps/helpdesk/src/components/index.js, packages/apps/helpdesk/src/components/molecules/TicketCard/TicketCard.tsx, packages/apps/helpdesk/src/components/templates/TicketSearchBar/TicketSearchBar.js, packages/apps/helpdesk/src/components/templates/index.js, packages/apps/helpdesk/src/features/index.js, packages/apps/helpdesk/src/features/ticketSlice.js, packages/apps/helpdesk/src/i18n/en.json, packages/apps/helpdesk/src/i18n/fr.json, packages/apps/helpdesk/src/index.ts, packages/apps/helpdesk/src/models/index.ts, packages/apps/helpdesk/src/models/objectFields.ts, packages/apps/helpdesk/src/models/searchFields.ts, packages/apps/helpdesk/src/models/sortFields.ts, packages/apps/helpdesk/src/screens/MyTicket/MyTicketListScreen.js, packages/apps/helpdesk/src/screens/MyTicket/index.js, packages/apps/helpdesk/src/types/ticket.tsx, packages/ui/src/components/organisms/ChipSelect/ChipSelect.tsx, yarn.lock
=> feat: add module entry myTickets

packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
=> fix: add refresh when list becomes empty

packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js, packages/apps/stock/src/components/templates/internalMove/InternalMoveSearchLineContainer/InternalMoveSearchLineContainer.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js, packages/apps/stock/src/features/customerDeliveryLineSlice.js, packages/apps/stock/src/features/internalMoveLineSlice.js, packages/apps/stock/src/features/supplierArrivalLineSlice.js, packages/apps/stock/src/i18n/en.json, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js, packages/apps/stock/src/types/index.ts, packages/apps/stock/src/types/stock-move-line.tsx, yarn.lock
=> fix: ignore isRealQtyModifiedByUser on realized StockMove

packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js, packages/apps/stock/src/screens/auth/UserScreen.js, packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js, packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx, yarn.lock
- set stock location search bar default value for the product details screen.
-  fix auto complete exceede renders.
RM#65228
=> fix: filter product stocks with user active stock location

packages/apps/stock/src/screens/internalMoves/InternalMoveLineCreationScreen.js
=> fix: internal move create screen fields visibilty

packages/apps/crm/src/components/templates/ContactSearchBar/ContactSearchBar.js, packages/apps/crm/src/screens/contact/ContactFormScreen.js, packages/apps/crm/src/screens/contact/ContactListScreen.js, yarn.lock
=> feat: add required on main partner in contact form view

packages/core/src/utils/image.ts, packages/ui/src/components/molecules/LabelText/LabelText.tsx, packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx, packages/ui/src/components/templates/index.js, packages/ui/stories/templates/ObjectCard.stories.tsx
=> feat: add new component ObjectCard

packages/apps/stock/src/components/templates/AvailableProductsSearchBar/AvailableProductsSearchBar.js, packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineCreationScreen.js, packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx, packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx, yarn.lock
=> fix: add scrollView in InternalMoveLineCreationScreen

packages/apps/crm/src/api/prospect-api.js, packages/apps/crm/src/components/molecules/PartnerCard/PartnerCard.tsx, packages/apps/crm/src/components/organisms/Prospect/ProspectHeader/ProspectHeader.js, packages/apps/crm/src/features/prospectSlice.js, packages/apps/crm/src/i18n/en.json, packages/apps/crm/src/i18n/fr.json, packages/apps/crm/src/models/objectFields.ts, packages/apps/crm/src/screens/prospect/ProspectDetailsScreen.js, packages/apps/crm/src/screens/prospect/ProspectsListScreen.js, packages/apps/crm/src/types/prospect.tsx
=> feat: add status display on Prospect views

packages/core/src/app/ContextedApplication.tsx, packages/core/src/auth/screens/SettingsScreen.js, packages/ui/src/components/molecules/BlockInteractionMessage/BlockInteractionMessage.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/src/config/ConfigContext.tsx, packages/ui/stories/molecules/BlockInteractionMessage.stories.tsx, yarn.lock
=> feat:  create component to block screen depending on config

packages/ui/src/components/atoms/Input/Input.tsx, packages/ui/src/components/molecules/IconInput/IconInput.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx, packages/ui/src/components/organisms/SearchBar/SearchBar.tsx, yarn.lock
=> fix: display issue in AutoCompleteSearch component

packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/SearchDetailsPopUp.tsx, yarn.lock
=> refactor: remove default value on details view to avoid input issue

packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductDetailsScreen.js, packages/apps/stock/src/components/organisms/QuantityCard/QuantityCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineQuantityCard/InternalMoveLineQuantityCard.js, packages/apps/stock/src/components/templates/inventory/InventoryLineQuantityCard/InventoryLineQuantityCard.tsx, packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionQuantityCard/StockCorrectionQuantityCard.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalAddTrackingScreen.js, packages/ui/src/components/atoms/Icon/Icon.tsx, packages/ui/src/components/molecules/FormIncrementInput/FormIncrementInput.tsx, packages/ui/src/components/molecules/Increment/Increment.tsx, packages/ui/src/components/molecules/Increment/IncrementButton.tsx, packages/ui/stories/molecules/FormIncrementInput.stories.tsx, packages/ui/stories/molecules/Increment.stories.tsx
RM#65687 
* add increment props isBigButton 
* set a big button for stock and manufactring quantity cards
=>  feat: Improve qty selector

packages/apps/helpdesk/src/api/customer-api.js, packages/apps/helpdesk/src/api/ticket-api.js, packages/apps/helpdesk/src/components/molecules/DurationFormInput/DurationFormInput.tsx, packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js, packages/apps/helpdesk/src/components/templates/TicketTypeSearchBar/TicketTypeSearchBar.js, packages/apps/helpdesk/src/components/templates/UserSearchBar/UserSearchBar.js, packages/apps/helpdesk/src/features/customerSlice.js, packages/apps/helpdesk/src/features/ticketSlice.js, packages/apps/helpdesk/src/i18n/en.json, packages/apps/helpdesk/src/i18n/fr.json, packages/apps/helpdesk/src/index.ts, packages/apps/helpdesk/src/models/objectFields.ts, packages/apps/helpdesk/src/models/searchFields.ts, packages/apps/helpdesk/src/models/sortFields.ts, packages/apps/helpdesk/src/screens/TicketFormScreen.js, yarn.lock
=> feat: add menu create ticket

packages/apps/crm/src/components/organisms/Opportunity/OpportunityUpdateStatusPicker/OpportunityUpdateStatusPicker.js, packages/apps/crm/src/screens/client/ClientFormScreen.js, packages/apps/crm/src/screens/contact/ContactFormScreen.js, packages/apps/crm/src/screens/lead/LeadFormScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityFormScreen.js, packages/apps/crm/src/screens/prospect/ProspectFormScreen.js, packages/apps/stock/src/components/organisms/QuantityCard/QuantityCard.tsx, packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineNotes/InternalMoveLineNotes.js, packages/apps/stock/src/components/templates/product/ProductCardInfo/ProductCardInfo.tsx, packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionReasonPicker/StockCorrectionReasonPicker.js, packages/apps/stock/src/screens/auth/UserScreen.js, packages/core/src/auth/screens/UserScreen.js, packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx, packages/ui/src/components/molecules/FormHtmlInput/FormHtmlInput.tsx, packages/ui/src/components/molecules/NotesCard/NotesCard.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx, yarn.lock
=> fix: alignment on form views

packages/apps/stock/src/components/molecules/StockCorrectionCard/StockCorrectionCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryCard/CustomerDeliveryCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveCard/InternalMoveCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx, packages/apps/stock/src/components/templates/inventory/InventoryCard/InventoryCard.tsx, packages/apps/stock/src/components/templates/inventory/InventoryLineCard/InventoryLineCard.tsx, packages/apps/stock/src/components/templates/product/ProductCard/ProductCard.tsx, packages/apps/stock/src/components/templates/product/ProductStockLocationCard/ProductStockLocationCard.tsx, packages/apps/stock/src/components/templates/product/ProductVariantCard/ProductVariantCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalCard/SupplierArrivalCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js, packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js, packages/apps/stock/src/screens/inventories/InventoryListScreen.js, packages/apps/stock/src/screens/products/ProductListScreen.js, packages/apps/stock/src/screens/products/ProductListVariantScreen.js, packages/apps/stock/src/screens/stockCorrections/StockCorrectionListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js, yarn.lock
=> refactor: simplify stock object cards

packages/apps/crm/src/components/molecules/CatalogCard/CatalogCard.tsx, packages/apps/crm/src/components/molecules/LeadsCard/LeadsCard.tsx, packages/apps/crm/src/components/molecules/LiteContactCard/LiteContactCard.tsx, packages/apps/crm/src/components/molecules/OpportunityCard/OpportunityCard.tsx, packages/apps/crm/src/components/molecules/PartnerCard/PartnerCard.tsx, packages/apps/crm/src/components/molecules/PartnerInfoCard/PartnerInfoCard.tsx, packages/apps/crm/src/components/molecules/PlanningEventCard/PlanningEventCard.tsx, packages/apps/crm/src/components/organisms/DropdownEmployeeView/DropdownEmployeeView.tsx
=> refactor: simplify crm object cards

packages/apps/helpdesk/src/components/molecules/TicketCard/TicketCard.tsx, packages/ui/src/theme/writingTheme.ts, yarn.lock
=> refactor: simplify helpdesk object cards

packages/apps/manufacturing/src/components/organisms/ConsumedProductCard/ConsumedProductCard.tsx, packages/apps/manufacturing/src/components/organisms/LinkedManufacturingOrderCard/LinkedManufacturingOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/ManufacturingOrderCard/ManufacturingOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/OperationOrderCard/OperationOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/OperationOrderDetailsCard/OperationOrderDetailsCard.tsx, packages/apps/manufacturing/src/components/organisms/ProducedProductCard/ProducedProductCard.tsx, packages/apps/manufacturing/src/components/organisms/WasteProductCard/WasteProductCard.tsx, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListSaleOrderScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderPlanningScreen.js, yarn.lock
=> refactor: simplify manufacturing object cards

packages/core/src/api/metafile-api.ts, packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx, packages/core/src/components/organisms/DateInput/DateInput.tsx, packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx, packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx, packages/ui/src/components/molecules/FormIncrementInput/FormIncrementInput.tsx, packages/ui/src/components/molecules/FormInput/FormInput.tsx, packages/ui/src/components/molecules/IconButton/IconButton.tsx, packages/ui/src/components/molecules/Increment/Increment.tsx, packages/ui/src/components/molecules/InfoBubble/InfoBubble.tsx, packages/ui/src/components/molecules/Label/Label.tsx, packages/ui/src/components/molecules/WarningCard/WarningCard.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx, packages/ui/src/components/organisms/Picker/Picker.tsx, packages/ui/src/utils/formatters.ts, packages/ui/stories/molecules/DropdownCard.stories.tsx, packages/ui/stories/molecules/FormIncrementInput.stories.tsx, packages/ui/stories/molecules/FormInput.stories.tsx, packages/ui/stories/molecules/Increment.stories.tsx, packages/ui/stories/molecules/InfoBubble.stories.tsx, packages/ui/stories/molecules/Label.stories.tsx
=> feat: improve standard components to prepare form generation

packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx, packages/core/src/i18n/hooks/use-translator.ts, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json
=> feat: manage max size and preview on UploadFileInput

packages/core/src/header/HeaderActionsProvider.ts, packages/core/src/header/index.ts, packages/core/src/navigator/drawer/Header.js, yarn.lock
=> fix: improve refresh logic of header actions

packages/apps/manufacturing/src/components/organisms/ConsumedProductCard/ConsumedProductCard.tsx, packages/apps/manufacturing/src/components/organisms/ManufacturingOrderCard/ManufacturingOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/ProducedProductCard/ProducedProductCard.tsx, packages/apps/manufacturing/src/components/organisms/WasteProductCard/WasteProductCard.tsx, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductDetailsScreen.js, packages/apps/stock/src/components/organisms/CardStockIndicator/CardStockIndicator.tsx, packages/apps/stock/src/components/organisms/QuantityCard/QuantityCard.tsx, packages/apps/stock/src/components/organisms/SmallPropertyCard/SmallPropertyCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryCard/CustomerDeliveryCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineQuantityCard/InternalMoveLineQuantityCard.js, packages/apps/stock/src/components/templates/inventory/InventoryLineCard/InventoryLineCard.tsx, packages/apps/stock/src/components/templates/inventory/InventoryLineQuantityCard/InventoryLineQuantityCard.tsx, packages/apps/stock/src/components/templates/product/ProductStockLocationCard/ProductStockLocationCard.tsx, packages/apps/stock/src/components/templates/product/ProductVariantCard/ProductVariantCard.tsx, packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionQuantityCard/StockCorrectionQuantityCard.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx, packages/apps/stock/src/screens/products/ProductStockLocationDetailsScreen.js, yarn.lock
=> refactor: apply digit system on functionnal modules

packages/apps/helpdesk/src/screens/TicketFormScreen.js, yarn.lock
=> feat: add props to reset date on Ticket form View

packages/apps/crm/src/components/molecules/PlanningEventCard/PlanningEventCard.tsx, packages/apps/crm/src/models/objectFields.ts, packages/apps/crm/src/screens/event/EventPlanningScreen.js, packages/apps/crm/src/types/event-type.ts
=> feat: display new field on EventPlanningCard

packages/apps/manufacturing/src/api/operation-order-api.js, packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js, packages/apps/manufacturing/src/features/operationOrderSlice.js, packages/apps/manufacturing/src/types/operation-order.tsx, packages/core/src/apiProviders/utils.ts, yarn.lock
=> feat: individualization of the operation order stopwatch

packages/apps/helpdesk/src/components/templates/TicketStopwatch/TicketStopwatch.js, packages/apps/helpdesk/src/components/templates/index.js, packages/apps/helpdesk/src/screens/TicketDetailsScreen.js, packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js, packages/core/src/components/external/Stopwatch/Stopwatch.tsx, packages/core/src/components/external/Timer/Timer.tsx, yarn.lock
=> fix: refresh issue on Stopwatch when app is inactive

packages/apps/hr/src/api/expense-api.js, packages/apps/hr/src/api/expense-line-api.js, packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx, packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.js, packages/apps/hr/src/components/molecules/index.js, packages/apps/hr/src/components/templates/ExpenseHeader/ExpenseHeader.tsx, packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx, packages/apps/hr/src/components/templates/index.js, packages/apps/hr/src/features/expenseLineSlice.js, packages/apps/hr/src/features/expenseSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/screens/ExpenseDetailsScreen.js, packages/apps/hr/src/screens/ExpenseLinesListScreen.js, packages/apps/hr/src/screens/ExpenseListScreen.js, packages/apps/hr/src/screens/index.js, packages/apps/hr/src/types/expense.tsx, yarn.lock
=> feat: add expense details view 

packages/core/src/features/cameraScannerSlice.ts, packages/core/src/features/scannerSlice.ts, packages/core/src/screens/SessionManagementScreen.js, packages/core/src/sessions/components/alerts/PopupCreateSession.js, packages/core/src/sessions/components/alerts/PopupEditSession.js, packages/core/src/sessions/components/display/SessionListCard.js, packages/core/src/sessions/components/inputs/SessionInputs.js, yarn.lock
=> fix: improve logic of session with camera

packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx, packages/ui/src/components/atoms/ScrollView/ScrollView.tsx, yarn.lock
=> feat: add props on ScrollView to manage pull to refresh

packages/core/src/api/model-api.ts, packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js, packages/core/src/header/hooks.js, packages/core/src/header/types.ts, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/navigator/Navigator.js, packages/core/src/navigator/drawer/Header.js, packages/core/src/screens/BarcodeDisplayScreen.tsx, packages/core/src/screens/index.js, packages/ui/src/components/molecules/Image/Image.tsx, yarn.lock
=> feat: add generic tool to display barcode

packages/core/src/components/pages/FormView/Components/Field.tsx, packages/core/src/components/pages/FormView/FormView.tsx, packages/core/src/forms/display.helpers.ts, packages/core/src/forms/types.ts, yarn.lock
=> feat: improve fields props with FormView

packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionButtons/StockCorrectionButtons.js, yarn.lock
=> fix: block user from saving if stock correction reason is empty

packages/core/src/components/templates/SocialNetworkLinks/SocialNetworkLinks.tsx, packages/core/src/components/templates/index.js, packages/core/src/tools/LinkingProvider.ts, yarn.lock
=> feat: add network links component

packages/core/src/components/pages/FormView/Components/Field.tsx, packages/core/src/forms/types.ts
=> feat: add readonlyIf props on field for FormView

packages/core/src/api/metafile-api.ts, packages/core/src/components/external/Camera/Camera.js, packages/core/src/components/external/Camera/CaptureButton.tsx, packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx, packages/core/src/features/cameraSlice.ts, yarn.lock
=> feat: improve upload input with camera option

packages/apps/hr/src/api/expense-api.js, packages/apps/hr/src/components/atoms/ExpenseCard/ExpenseCard.tsx, packages/apps/hr/src/components/molecules/ExpenseAddPopup/ExpenseAddPopup.js, packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js, packages/apps/hr/src/features/expenseSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/screens/ExpenseDetailsScreen.js, packages/apps/hr/src/screens/ExpenseLinesListScreen.js, packages/apps/hr/src/screens/ExpenseListScreen.js, packages/apps/hr/src/types/expense.tsx
=> feat: add API request on buttons

packages/apps/hr/src/api/expense-api.js, packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js, packages/apps/hr/src/components/molecules/ExpenseRefusalPopup/ExpenseRefusalPopup.js, packages/apps/hr/src/components/molecules/index.js, packages/apps/hr/src/features/expenseSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json
=> feat: add the possibility the reject an expense waiting validation

packages/apps/hr/src/api/expense-line-api.js, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.js, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx, packages/apps/hr/src/features/expenseLineSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/ExpenseLinesListScreen.js
=> feat: add possibility to delete orphan expenseLine

packages/ui/package.json, packages/ui/src/components/atoms/RadioButton/RadioButton.tsx, packages/ui/src/components/atoms/index.tsx, packages/ui/src/components/molecules/RadioSelect/RadioSelect.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/stories/atoms/RadioButton.stories.tsx, packages/ui/stories/molecules/RadioSelect.stories.tsx
=> feat: add RadioSelect component

packages/apps/hr/src/components/templates/ToggleSwitchMode/ToggleSwitchMode.js, packages/apps/hr/src/models/forms.ts
=> feat: replace toggle mode component

packages/apps/hr/src/api/kilometric-allow-param-api.js, packages/apps/hr/src/components/templates/KilometricAllowParamSearchBar/KilometricAllowParamSearchBar.js, packages/apps/hr/src/features/kilometricAllowParamSlice.js, packages/apps/hr/src/models/forms.ts, packages/core/src/components/pages/FormView/FormView.tsx, packages/core/src/forms/types.ts
=> feat: manage kap on Date

packages/apps/hr/src/screens/ExpenseLineFormScreen.js
=> fix: add default value for expense date

packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx, yarn.lock
=> refactor: improve expense line card

packages/apps/hr/src/api/currency-api.js, packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx, packages/apps/hr/src/components/templates/BillableSwitchCard/BillableSwitchCard.tsx, packages/apps/hr/src/components/templates/CurrencySearchBar/CurrencySearchBar.js, packages/apps/hr/src/components/templates/index.js, packages/apps/hr/src/features/currencySlice.js, packages/apps/hr/src/features/index.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/models/forms.ts, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/models/searchFields.ts, packages/apps/hr/src/screens/ExpenseLineFormScreen.js
=> feat: manage mobile settings configuration on form

packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryCard/CustomerDeliveryCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveCard/InternalMoveCard.tsx, packages/apps/stock/src/components/templates/product/ProductCardInfo/ProductCardInfo.tsx, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryDetailScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveDetailsGeneralScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js, packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js, packages/apps/stock/src/screens/inventories/InventoryPlannedDetailsScreen.js, packages/apps/stock/src/screens/inventories/InventoryStartedDetailsScreen.js, packages/apps/stock/src/screens/products/ProductDetailsScreen.js, packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js, packages/apps/stock/src/screens/stockCorrections/StockCorrectionDetailsScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalDetailsScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
=> refactor: add pull to refresh on stock package

packages/core/src/api/metafile-api.ts, packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx, yarn.lock
=> feat: improve UploadFileInput

.github/workflows/gradle.yml
=> feat: add branch name in artifact

packages/apps/hr/src/hooks/use-hr-header-actions.js, packages/apps/hr/src/index.ts, packages/apps/hr/src/screens/ExpenseDetailsScreen.js, packages/apps/hr/src/screens/index.js, yarn.lock
=> feat: add action menu for refresh

packages/apps/crm/src/screens/client/ClientDetailsScreen.js, packages/apps/crm/src/screens/contact/ContactDetailsScreen.js, packages/apps/crm/src/screens/event/EventDetailsScreen.js, packages/apps/crm/src/screens/lead/LeadDetailsScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityDetailsScreen.js, packages/apps/crm/src/screens/prospect/ProspectDetailsScreen.js
=> feat: add pull to refresh for crm details screen

packages/apps/helpdesk/src/screens/TicketDetailsScreen.js
=> feat: add pull to refresh on Helpdesk details screen

packages/apps/crm/src/api/partner-api.js, packages/apps/crm/src/components/organisms/Contact/ContactDropdownCards/ContactDropdownCards.js, packages/apps/crm/src/components/organisms/DropdownContactPartnerView/DropdownContactPartnerView.js, packages/apps/crm/src/components/organisms/index.js, packages/apps/crm/src/features/partnerSlice.js, packages/apps/crm/src/i18n/en.json, packages/apps/crm/src/i18n/fr.json, yarn.lock
=> feat: add client on contact details screens

packages/ui/src/components/molecules/InfoBubble/InfoBubble.tsx, yarn.lock
=> feat: add coloredBubble props on InfoBubble

packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js
=> fix: modify category on prospect dropdown

packages/apps/crm/src/components/organisms/DropdownContactView/DropdownContactView.tsx
=> fix: modify display condition in DropdownContactView

packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx
=> fix: modification of arrow icon position

packages/apps/stock/src/components/templates/inventory/InventoryButtons/InventoryButtons.js
=> refactor: check uses of Button in stock package

packages/apps/helpdesk/src/components/templates/TicketStopwatch/TicketStopwatch.js, packages/apps/helpdesk/src/components/templates/TicketsStatusButton/TicketsStatusButton.js
=> refactor: check uses of Button in helpdesk package

packages/apps/hr/src/screens/ExpenseLineFormScreen.js
=> feat: add expense date in store when oppening form

packages/apps/crm/src/api/opportunities-api.js, packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js, packages/apps/crm/src/components/organisms/DropdownEventView/DropdownEventView.tsx, packages/apps/crm/src/components/organisms/DropdownOpportunityView/DropdownOpportunityView.tsx, packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js, packages/apps/crm/src/components/organisms/index.js, packages/apps/crm/src/features/opportunitySlice.js, packages/apps/crm/src/i18n/en.json, packages/apps/crm/src/i18n/fr.json, packages/apps/crm/src/utils/dateEvent.js, packages/apps/crm/src/utils/list.js
=> feat: display last opportunity on prospect

packages/ui/src/components/atoms/Switch/Switch.tsx
=> fix: Switch refresh when default value changes

packages/apps/manufacturing/src/components/organisms/ManufacturingOrderButtons/ManufacturingOrderButtons.js, packages/apps/manufacturing/src/components/organisms/index.js, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderDetailsScreen.js, packages/ui/src/utils/commons-styles.js
=> refactor: check uses of Button in manufacturing package

packages/ui/src/components/molecules/Button/Button.tsx, packages/ui/src/components/molecules/CircleButton/CircleButton.tsx, packages/ui/src/components/organisms/FloatingButton/FloatingButton.tsx, packages/ui/src/utils/commons-styles.js, packages/ui/stories/molecules/CircleButton.stories.tsx
=> refactor: improve CircleButton to match new design of Button

packages/core/src/components/pages/FormView/Alerts/ConstraintsValidatorPopup.tsx, packages/core/src/components/templates/MailMessageView/MailMessageView.js, packages/core/src/components/templates/PopupApplicationNotConfigured/PopupApplicationNotConfigured.js, packages/core/src/components/templates/PopupMinimalRequiredVersion/PopupMinimalRequiredVersion.js, packages/core/src/sessions/components/alerts/PopupCreateSession.js, packages/core/src/sessions/components/alerts/PopupEditSession.js, packages/core/src/sessions/components/alerts/PopupSession.js, packages/ui/src/components/molecules/Alert/Alert.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/SearchDetailsPopUp.tsx
=> refactor: replace PopUp on core, error and ui packages by Alert and small fixes on Alert

packages/apps/manufacturing/src/components/organisms/OperationOrderLabelTextList/OperationOrderLabelTextList.tsx, packages/apps/manufacturing/src/i18n/en.json, packages/apps/manufacturing/src/i18n/fr.json, packages/apps/manufacturing/src/models/objectFields.ts
=> feat: add planned durations on OperationOrder

packages/apps/hr/src/components/molecules/ExpenseAddPopup/ExpenseAddPopup.js, packages/apps/hr/src/components/molecules/ExpenseRefusalPopup/ExpenseRefusalPopup.js
=> refactor: replace PopUp on hr package by Alert

packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductListScreen.js
=> refactor: replace PopUp on manufacturing package by Alert

packages/apps/hr/src/api/expense-type-api.js, packages/apps/hr/src/components/templates/ExpenseTypeSearchBar/ExpenseTypeSearchBar.js, packages/apps/hr/src/models/forms.ts, packages/apps/hr/src/models/objectFields.ts
=> fix: HR prevent user from completing informations depending on config

packages/apps/stock/src/components/organisms/CardStockIndicator/CardStockIndicator.tsx, packages/apps/stock/src/components/organisms/SmallPropertyCard/SmallPropertyCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryMovementIndicationCard/CustomerDeliveryMovementIndicationCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalMovementIndicationCard/SupplierArrivalMovementIndicationCard.tsx, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectProductScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectTrackingScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveSelectProductScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveSelectTrackingScreen.js, packages/apps/stock/src/screens/inventories/InventorySelectProductScreen.js, packages/apps/stock/src/screens/inventories/InventorySelectTrackingScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectProductScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectTrackingScreen.js, packages/ui/src/components/molecules/Alert/Alert.tsx
=> refactor: replace PopUp on stock package by Alert

packages/core/src/utils/filter.ts, packages/core/src/utils/index.ts
=> feat: add helper to create Criteria depdending on selected chips

packages/apps/hr/src/models/forms.ts
=> fix: reset tax input when selecting type which block tax amount

nx.json, package.json
=> fix: fix yarn dev

packages/apps/crm/src/api/index.ts, packages/apps/crm/src/features/asyncFunctions-index.ts, packages/apps/crm/src/hooks/index.ts, packages/apps/crm/src/index.ts, packages/apps/crm/src/screens/catalog/index.js, packages/apps/crm/src/screens/client/index.js, packages/apps/crm/src/screens/event/index.js, packages/apps/crm/src/screens/lead/index.js, packages/apps/crm/src/screens/opportunity/index.js, packages/apps/crm/src/screens/prospect/index.js, packages/apps/crm/src/utils/index.ts
=> fix: export content of crm package to allow external package to use it

packages/ui/src/components/atoms/Screen/Screen.tsx
=> fix: remove white bar which appears on some screens

__mocks__/react-native-vector-icons/FontAwesome.js, __mocks__/react-native-vector-icons/FontAwesome5.js, jest/setup-mocks.js, packages/ui/__tests__/components/atoms/BlockInteractionScreen.test.js, packages/ui/__tests__/components/atoms/Card.test.js, packages/ui/__tests__/components/atoms/DottedLine.test.js, packages/ui/__tests__/components/atoms/HorizontalRule.test.js, packages/ui/__tests__/components/atoms/HtmlInput.test.js, packages/ui/__tests__/components/atoms/Icon.test.js, packages/ui/__tests__/components/atoms/Input.test.js, packages/ui/__tests__/components/atoms/KeyboardAvoidingScrollView.test.js, packages/ui/__tests__/components/atoms/RadioButton.test.js, packages/ui/__tests__/components/atoms/Screen.test.js, packages/ui/__tests__/components/atoms/ScrollView.test.js, packages/ui/__tests__/components/atoms/Switch.test.js, packages/ui/__tests__/components/atoms/Text.test.js, packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
=> test: add test cases for UI atoms components

packages/core/src/components/external/Stopwatch/Stopwatch.tsx, packages/ui/src/components/atoms/Icon/Icon.tsx
=> refactor: deletion of disabled props from Icon component

packages/ui/src/components/organisms/AutoCompleteSearch/ItemCard.tsx
=> fix: long titles exceed on SearchDetailsPopUp

packages/apps/hr/src/components/atoms/ExpenseCard/ExpenseCard.tsx, packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx, packages/apps/hr/src/screens/ExpenseDetailsScreen.js, packages/apps/hr/src/screens/ExpenseListScreen.js, packages/core/src/components/organisms/AnomalyBubble/AnomalyBubble.tsx, packages/core/src/components/organisms/AnomalyList/AnomalyList.tsx
=> feat: added check for anomalies on Expense and ExpenseLine

packages/core/src/components/molecules/CameraButton/CameraButton.tsx
=> fix: remove the border from CameraButton

packages/apps/crm/src/api/index.ts, packages/apps/crm/src/features/asyncFunctions-index.ts, packages/apps/crm/src/screens/event/index.js, packages/apps/crm/src/utils/index.ts, packages/apps/manufacturing/src/features/asyncFunctions-index.ts
=> fix: export content of all apps to allow external package to re-use it

packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx
=> fix: modification of ObjectCard to allow more flexibility

packages/ui/__tests__/components/molecules/Increment.test.js, packages/ui/src/components/molecules/Increment/Increment.tsx, yarn.lock
=> test: add test cases for Increment component

packages/core/src/apiProviders/utils.ts
=> fix: some API request error was shown as success

packages/ui/__tests__/components/molecules/Alert.test.js
=> feat: add test cases for Alert component

packages/ui/__tests__/components/molecules/NotesCard.test.js
=> test: add test cases for NotesCard component

packages/ui/__tests__/components/molecules/PanelTabs.test.js
=> feat: add test cases for PanelTabs component

packages/ui/__tests__/components/molecules/NumberBubble.test.js, yarn.lock
=> feat: add numberBubble test

packages/ui/src/components/atoms/Icon/Icon.tsx
=> fix: undefined color in darkMode

packages/apps/hr/src/components/molecules/ExpenseAddPopup/ExpenseAddPopup.js, packages/apps/hr/src/components/templates/CurrencySearchBar/CurrencySearchBar.js, packages/apps/hr/src/components/templates/ExpenseTypeSearchBar/ExpenseTypeSearchBar.js, packages/apps/hr/src/components/templates/KilometricAllowParamSearchBar/KilometricAllowParamSearchBar.js, packages/apps/hr/src/components/templates/KilometricTypeSelectPicker/KilometricTypeSelectPicker.js, packages/apps/hr/src/components/templates/ProjectSearchBar/ProjectSearchBar.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js, packages/core/src/components/pages/FormView/Custom/CustomPicker.tsx, packages/core/src/components/pages/FormView/Custom/CustomSearchBar.tsx
=> refactor: simplification of uses of Picker and SearchBar to match refactor done on dev branch

packages/apps/hr/src/components/atoms/ExpenseCard/ExpenseCard.tsx, packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx, packages/apps/hr/src/screens/ExpenseListScreen.js, yarn.lock
=> fix: modification of price display on Expense lines and Expenses

packages/ui/__tests__/components/molecules/PopUp.test.js
=> feat: add test for popUp

packages/ui/__tests__/components/molecules/RightIconButton.test.js
=> feat: add test for RightIconButton

packages/ui/__tests__/components/molecules/TitledValue.test.js
=> feat: add test for titledValue

packages/ui/__tests__/components/molecules/SwitchCard.test.js, yarn.lock
=> feat: add SwitchCard test

packages/ui/__tests__/components/molecules/ToggleSwitch.test.js, yarn.lock
=> feat: add ToggleSwitch test

packages/core/src/api/mobile-config-api.ts, packages/core/src/apiProviders/utils.ts, src/app.config.js, yarn.lock
=> fix: manage AOP errors on API request

packages/ui/__tests__/components/molecules/StarScore.test.js
=> test: add cases for StarScore component

packages/ui/__tests__/components/molecules/RadioSelect.test.js
=> test: add cases for RadioSelect component

packages/ui/__tests__/components/molecules/ViewAllContainer.test.js
=> test: add test for ViewAllContainer component

packages/ui/__tests__/components/molecules/WarningCard.test.js
=> test: add cases for WarningCard component

packages/ui/__tests__/components/molecules/UnorderedList.test.js
=> test: add cases for UnorderedList component

packages/apps/stock/src/components/templates/product/ProductStockLocationCard/ProductStockLocationCard.tsx
=> fix: remove arrow icon on non clickable card

packages/ui/__tests__/components/organisms/DropdownCardSwitch.test.js
=> feat: add test for DropdownCardSwitch

packages/ui/__tests__/components/molecules/SelectionContainer.test.js
=> test: add cases for SelectionContainer component

packages/ui/__tests__/components/organisms/FloatingButton.test.js
=> feat: add test cases for FloatingButton component

docs/doc/en/Application/Creation_d_un_ecran.md, docs/doc/fr/Application/Creation_d_un_ecran.md, packages/core/src/components/pages/FormView/Components/Panel.tsx, packages/core/src/forms/studio/display.helpers.ts, packages/core/src/forms/types.ts
=> fix: add flexDirection props to collapsible pannel in forms

packages/ui/__tests__/components/organisms/ChipSelect.test.js, packages/ui/src/components/organisms/ChipSelect/ChipSelect.tsx
=> feat: add test cases for ChipSelect component

packages/ui/__tests__/components/organisms/DropdownMenuItem.test.js
=> feat: add test cases for DropdownMenuItem component

packages/core/src/components/molecules/FocusScreen/FocusScreen.tsx, packages/core/src/components/molecules/index.js
=> feat: generalize isFocused management

.storybook/preview.js
=> fix: manage FontAwesome icon display on storybook

packages/ui/__tests__/components/organisms/HeaderContainer.test.js, packages/ui/src/components/organisms/HeaderContainer/HeaderContainer.tsx
=> feat: add test cases for HeaderContainer component

packages/ui/__tests__/components/organisms/ImageBubble.test.js
=> feat: add test cases for ImageBubble component

packages/ui/__tests__/components/organisms/AutoCompleteSearch.test.js
=> feat: add test cases for AutoCompleteSearch component

packages/ui/__tests__/components/organisms/GroupByScrollList.test.js, packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/GroupByScrollList.stories.tsx
=> feat: creation of GroupByScrollList component

packages/apps/hr/src/features/distanceSlice.js
=> fix: refresh issue on distanceInput

packages/apps/hr/src/features/expenseLineSlice.js
=> fix: refresh issue on expense details when editing expense line

packages/core/src/sessions/components/inputs/SessionInputs.js
=> fix: invalid url error stay on all popup

packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
=> feat: add icon Expense buttons

packages/apps/hr/src/components/templates/ExpenseHeader/ExpenseHeader.tsx, packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/models/objectFields.ts
=> feat: add label for groundForRefusal

packages/core/src/api/net-info-utils.ts, packages/core/src/sessions/components/error/ErrorText.js, yarn.lock
=> fix: session expired after 2minutes on AOP7

packages/ui/stories/atoms/Icon.stories.tsx
=> feat: add Icon stories

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/features/asyncFunctions-index.ts
=> fix: add missing exports in HR

packages/apps/hr/src/components/templates/KilometricAllowParamSearchBar/KilometricAllowParamSearchBar.js
=> fix: refresh issue on KilometricAllowParamSearchBar

packages/apps/hr/src/api/employee-api.js, packages/apps/hr/src/api/index.ts, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/employeeSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/ExpenseListScreen.js
=> feat: add condition to display toogle depends on manage employee

packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, src/app.config.js, yarn.lock
=> feat: add city, and distance on kilometric expense line card

packages/ui/__tests__/components/molecules/DoubleIcon.test.js, packages/ui/src/components/molecules/DoubleIcon/DoubleIcon.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/stories/molecules/DoubleIcon.stories.tsx, yarn.lock
=> feat: add DoubleIcon component

packages/apps/manufacturing/src/components/organisms/OperationOrderHeader/OperationOrderHeader.tsx, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderPlanningScreen.js, packages/apps/manufacturing/src/types/operation-order.tsx, packages/core/src/components/external/PlanningView/agenda.helpers.ts, yarn.lock
=> feat: feat npe in Manufacturing PlanningView

packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js, packages/apps/helpdesk/src/screens/MyTicketListScreen.js, packages/apps/helpdesk/src/types/ticket.tsx
=> fix: Helpdesk change default selected chip

packages/ui/__tests__/components/organisms/GroupByScrollList.test.js, packages/ui/src/components/organisms/GroupByScrollList/BottomSeparator.tsx, packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx, packages/ui/src/components/organisms/GroupByScrollList/TopSeparator.tsx, packages/ui/stories/organisms/GroupByScrollList.stories.tsx, yarn.lock
=> feat: improve design of GroupByScrolllist

packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/ExpenseLinesListScreen.js
=> feat: add DoubleIcon in ExpenseLine header to open selection mode

packages/ui/__tests__/components/organisms/ToggleButton.test.js, packages/ui/src/components/organisms/ToggleButton/ToggleButton.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/ToggleButton.stories.tsx, yarn.lock
=> feat: add ToggleButton Component

packages/core/src/sessions/components/inputs/SessionInputs.js
=> fix: invalid url error appears when typing

packages/apps/stock/src/features/inventorySlice.js
=> fix: inventory update when return error 

packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
=> fix: manage refresh on page after reaching end of list

packages/core/src/sessions/components/alerts/PopupCreateSession.js, packages/core/src/sessions/components/alerts/PopupSession.js
=> feat: disabled close button of Alert when login

packages/apps/stock/src/features/inventorySlice.js
=> fix: update list when update inventory

packages/apps/stock/src/components/molecules/StockCorrectionCard/StockCorrectionCard.tsx
=> fix: error message when going on StockCorrection menu entry

packages/apps/hr/src/models/sortFields.ts
=> fix: reverse order of expense list view

packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
=> fix: Selection container when content is null

packages/core/src/forms/studio/display.helpers.ts, packages/core/src/forms/studio/formula.helpers.ts, packages/core/src/forms/studio/index.ts, packages/core/src/screens/JsonFieldScreen.tsx, packages/core/src/utils/object.ts, packages/ui/src/components/atoms/Input/Input.tsx
=> feat: add management of js formula on studio form

packages/apps/hr/src/components/atoms/DatesInterval/DatesInterval.tsx, packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx, packages/apps/hr/src/components/atoms/index.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json
=> feat: improve TimesheetCard

packages/apps/hr/src/api/expense-api.js, packages/apps/hr/src/api/index.ts, packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/expenseSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/expense/ExpenseListScreen.js, packages/core/src/components/organisms/AnomalyBubble/AnomalyBubble.tsx
=>  feat: add possibility to delete a draft expense

packages/core/src/components/pages/FormView/Components/Field.tsx, packages/core/src/forms/types.ts
=> feat: add possibility to get all values of object form from view fields

packages/apps/hr/src/components/templates/DraftExpensePicker/DraftExpensePicker.js
=> fix: draft expense picker title not translated

packages/apps/manufacturing/src/features/prodProductSlice.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js
=> fix: refresh issue on consumedProduct tracking number update

packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/ui/__tests__/components/molecules/Checkbox.test.js, packages/ui/__tests__/components/organisms/CheckboxScrollList.test.js, packages/ui/src/components/molecules/Checkbox/Checkbox.tsx, packages/ui/src/components/organisms/CheckboxScrollList/CheckboxScrollList.tsx, packages/ui/src/components/organisms/ScrollList/ScrollList.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/molecules/Checkbox.stories.tsx, packages/ui/stories/organisms/CheckboxScrollList.stories.tsx
=> feat: add CheckboxScrollList component

packages/ui/__tests__/components/atoms/Icon.test.js, packages/ui/src/components/atoms/Icon/Icon.tsx
=> feat: adapt Icon component for BootstrapIcon

packages/core/src/auth/features/userSlice.js, packages/core/src/auth/i18n/en.json, packages/core/src/auth/i18n/fr.json, packages/core/src/auth/screens/UserScreen.js, packages/core/src/components/templates/PopupApplicationInformation/PopupApplicationInformation.tsx, packages/core/src/components/templates/index.js, packages/core/src/navigator/drawer/DrawerContent.js
=> feat: block access to the application if user cannot be fetched

packages/ui/__tests__/components/templates/BarChart.test.js, packages/ui/__tests__/components/templates/Dashboard.test.js, packages/ui/__tests__/components/templates/LineChart.test.js, packages/ui/__tests__/components/templates/PieChart.test.js
=> feat: add test cases for Dashboard components

packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js, packages/apps/crm/src/components/organisms/Lead/LeadDropdownCards/LeadDropdownCards.js, packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js
=> fix: add condition before dispatch to prevent undefined fetch

packages/ui/__tests__/components/atoms/BootstrapIcon.test.js, packages/ui/src/components/atoms/BootstrapIcon/BootstrapIcon.tsx
=> feat: add test cases for BootstrapIcon component

packages/ui/stories/templates/Dashboard/BarChart.stories.tsx, packages/ui/stories/templates/Dashboard/Dashboard.stories.tsx, packages/ui/stories/templates/Dashboard/LineChart.stories.tsx, packages/ui/stories/templates/Dashboard/PieChart.stories.tsx
=> feat: add stories for Dashboard components

packages/apps/helpdesk/src/components/molecules/DurationFormInput/duration.helpers.ts
=> fix: npe when null

packages/apps/crm/src/screens/catalog/CatalogListScreen.js, packages/apps/crm/src/screens/client/ClientsListScreen.js, packages/apps/crm/src/screens/contact/ContactListScreen.js, packages/apps/crm/src/screens/event/EventPlanningScreen.js, packages/apps/crm/src/screens/lead/LeadListScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js, packages/apps/crm/src/screens/prospect/ProspectsListScreen.js, packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js, packages/apps/helpdesk/src/screens/MyTicketListScreen.js, packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx, packages/apps/hr/src/screens/ExpenseListScreen.js, packages/ui/src/components/molecules/ToggleSwitch/ToggleSwitch.tsx
=> refactor: improve ToggleSwitch styles

packages/apps/helpdesk/src/components/templates/MyTeamTicketSearchBar/MyTeamTicketSearchBar.js, packages/apps/helpdesk/src/components/templates/MyTicketSearchBar/MyTicketSearchBar.js, packages/apps/helpdesk/src/components/templates/TicketSearchBar/TicketSearchBar.js, packages/apps/helpdesk/src/components/templates/index.js, packages/apps/helpdesk/src/features/asyncFunctions-index.ts, packages/apps/helpdesk/src/features/ticketSlice.js, packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js, packages/apps/helpdesk/src/screens/MyTicketListScreen.js
=> fix : add new slice for myTeamTicket to avoid refresh issue

packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js, packages/ui/__tests__/components/molecules/CircleButton.test.js, packages/ui/src/components/molecules/CircleButton/CircleButton.tsx, packages/ui/src/components/molecules/IconInput/IconInput.tsx, packages/ui/src/components/molecules/Label/Label.tsx, packages/ui/src/components/molecules/MessageBox/MessageBox.tsx, packages/ui/src/components/molecules/NotesCard/NotesCard.tsx, packages/ui/src/components/molecules/RightIconButton/RightIconButton.tsx, packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx, packages/ui/src/utils/commons-styles.js
=> feat: match input display to AOPv7 design

packages/ui/src/components/molecules/ToggleSwitch/ToggleSwitch.tsx
=> fix: display issue on ToggleSwitch due to new input design

packages/ui/__tests__/components/organisms/MultiValuePicker.test.js, packages/ui/src/utils/list.tsx, packages/ui/stories/organisms/MultiValuePicker.stories.tsx
=> feat: add test cases for MultiValuePicker component

packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
=> fix: avoid page reset when the next is loading

packages/ui/__tests__/components/templates/BarChart.test.js, packages/ui/src/components/templates/Dashboard/Chart/BarChart.tsx, packages/ui/src/components/templates/Dashboard/Chart/LineChart.tsx, packages/ui/src/components/templates/Dashboard/Chart/chart.helper.ts, packages/ui/src/components/templates/Dashboard/dashboard.helper.ts
=> feat: add rotation to label

packages/ui/__tests__/components/molecules/Checkbox.test.js, packages/ui/__tests__/components/organisms/CheckboxScrollList.test.js, packages/ui/src/components/molecules/Checkbox/Checkbox.tsx, packages/ui/src/components/organisms/CheckboxScrollList/CheckboxScrollList.tsx
=> feat: add indicator of partial selection on CheckBoxScrollList

packages/ui/__tests__/components/organisms/GroupByScrollList.test.js, packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx
=> fix: no bottom indicator on last item in GroupByScrollList

packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionButtons/StockCorrectionButtons.js
=> fix: change icons of stock correction buttons

packages/apps/hr/src/components/atoms/DateDisplay/DateDisplay.tsx, packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx, packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js, packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx, packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx, packages/apps/hr/src/hooks/use-hr-header-actions.js, packages/apps/hr/src/index.ts
=> refactor: migrate icon to boostrap icon

docs/doc/en/Application/Creation_d_un_ecran.md, docs/doc/en/Application/Creation_d_un_module.md, docs/doc/en/Application/Gestion_des_composants.md, docs/doc/en/Outil/Gestion_des_headers.md, docs/doc/fr/Application/Creation_d_un_ecran.md, docs/doc/fr/Application/Creation_d_un_module.md, docs/doc/fr/Application/Gestion_des_composants.md, docs/doc/fr/Outil/Gestion_des_headers.md, packages/ui/__tests__/components/atoms/Icon.test.js, packages/ui/src/components/atoms/Icon/Icon.tsx
=> refactor: remove FontAwesome5 props

packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js, packages/apps/helpdesk/src/screens/MyTicketListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderOperationListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ChildrenManufOrderListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js, packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js, packages/apps/stock/src/screens/inventories/InventoryListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js, packages/core/src/components/templates/AttachedFilesView/AttachedFilesView.js
=> feat: apply default configurations on ChipSelect uses

packages/ui/src/components/molecules/Alert/Alert.tsx
=> feat: add buttonsContainerStyle props to Alert component

packages/core/src/forms/FormConfigsProvider.ts
=> fix: refresh issue on form fields when multiple uses of associated hook

packages/core/src/app/Module.ts, packages/core/src/navigator/drawer/MenuItem.js, packages/core/src/navigator/drawer/MenuSeparator.js
=> feat: add MenuSeparator

packages/ui/__tests__/components/molecules/NumberChevronInput.test.js, packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx, packages/ui/stories/molecules/NumberChevronInput.stories.tsx
=> fix: refactor NumberChevronInput to avoid duplicate code

packages/ui/src/components/organisms/Picker/Picker.tsx
=> fix: make the labelField props not required on Picker component

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/api/timesheet-api.js, packages/apps/hr/src/api/timesheet-line-api.js, packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx, packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx, packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx, packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx, packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx, packages/apps/hr/src/components/molecules/index.js, packages/apps/hr/src/components/templates/TimesheetFilters/TimesheetFilters.js, packages/apps/hr/src/components/templates/index.js, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/index.js, packages/apps/hr/src/features/timesheetLineSlice.js, packages/apps/hr/src/features/timesheetSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/index.ts, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/models/searchFields.ts, packages/apps/hr/src/models/sortFields.ts, packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js, packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js, packages/apps/hr/src/screens/timesheet/index.ts, packages/apps/hr/src/types/time.ts, packages/apps/hr/src/types/timesheet.ts, packages/apps/hr/src/utils/index.ts, packages/apps/hr/src/utils/unit.ts
=> feat: create Timesheet details view

packages/core/src/app/RootNavigator.js, packages/core/src/header/hooks.js
=> fix: internet connection issue

packages/core/src/components/external/PlanningView/PlanningView.tsx
=> refactor: change PlanningView calendar icon

packages/apps/hr/src/screens/timesheet/index.ts
=> fix: remove shaded header on timesheet screens when needed

packages/apps/hr/src/screens/timesheet/TimerListScreen.js
=> fix: duration on TimerListScreen

packages/core/src/components/organisms/DateInput/DateInput.tsx
=> feat: add props on DateInput to put selection container on full screen

packages/core/src/components/external/PlanningView/PlanningView.tsx, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json
=> feat: add assignation filter on calendar

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/api/timer-api.js, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/timerSlice.js, packages/apps/hr/src/hooks/use-hr-header-actions.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/models/sortFields.ts, packages/apps/hr/src/screens/timesheet/TimerFormScreen.js, packages/apps/hr/src/screens/timesheet/TimerListScreen.js
=> feat: fetch active timer when coming from menu entry

packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx, packages/apps/hr/src/models/forms.ts, packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js, packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js
=> feat: link TimesheeLine to form view

packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
=> feat: automatically fill timer activity with employee configuration

packages/apps/quality/src/api/control-entry-api.js, packages/apps/quality/src/api/control-entry-sample-line-api.js, packages/apps/quality/src/api/index.ts, packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx, packages/apps/quality/src/components/molecules/ControlEntryDetailsButtons/ControlEntryDetailsButtons.tsx, packages/apps/quality/src/components/molecules/ControlEntryDetailsHeader/ControlEntryDetailsHeader.tsx, packages/apps/quality/src/components/molecules/ControlEntryHeader/ControlEntryHeader.tsx, packages/apps/quality/src/components/molecules/index.js, packages/apps/quality/src/features/asyncFunctions-index.ts, packages/apps/quality/src/features/controlEntrySampleSlice.js, packages/apps/quality/src/features/controlEntrySlice.js, packages/apps/quality/src/features/index.js, packages/apps/quality/src/i18n/en.json, packages/apps/quality/src/i18n/fr.json, packages/apps/quality/src/models/objectFields.ts, packages/apps/quality/src/models/sortFields.ts, packages/apps/quality/src/screens/ControlEntryDetailsScreen.js, packages/apps/quality/src/screens/ControlEntryListScreen.js, packages/apps/quality/src/screens/index.js, packages/apps/quality/src/types/controlEntry.tsx
=> feat: add ControlEntryDetailsScreen

packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js
=> fix: hide delete button when TimesheetLine is linked to TSTimer

packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx, packages/apps/hr/src/components/templates/TimesheetRefusalPopup/TimesheetRefusalPopup.tsx, packages/apps/hr/src/features/timesheetSlice.js, packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js
=> fix: number timesheet to validate refresh issue

packages/apps/hr/src/features/timesheetLineSlice.js
=> fix: timesheet not refresh when modify

packages/apps/hr/src/components/atoms/DatesInterval/DatesInterval.tsx, packages/core/src/utils/object.ts
=> fix: same start and end date on DatesInterval

packages/apps/hr/src/components/templates/DraftTimesheetPicker/DraftTimesheetPicker.tsx, packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx, packages/apps/hr/src/features/timesheetSlice.js
=> fix: can't re-open declare form after one declaration

packages/apps/hr/src/index.ts
=> feat: add compatibility on Timesheet menus

packages/apps/hr/src/components/molecules/TimesheetCreationAlert/TimesheetCreationAlert.tsx, packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx, packages/apps/hr/src/components/molecules/index.js, packages/apps/hr/src/features/timesheetSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js, packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js, packages/apps/hr/src/screens/timesheet/index.ts
=> feat: add manual creation of timesheet

packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx
=> fix: remove TouchableOpacity on control entry sample card

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/api/timer-api.js, packages/apps/hr/src/components/molecules/TimerStopwatch/TimerStopwatch.tsx, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/timerSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/timesheet/TimerFormScreen.js, packages/apps/hr/src/screens/timesheet/TimerListScreen.js, packages/apps/hr/src/types/time.ts
=> feat: add timer requests

packages/core/src/navigator/menu.helper.js
=> fix: filter only compatible menus for default module action

packages/core/src/header/HeaderActionsProvider.ts
=> refactor: improve header action refresh management

packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx, packages/apps/quality/src/features/controlEntrySampleLineSlice.js, packages/apps/quality/src/screens/ControlEntryDetailsScreen.js
=> fix: add focusScreen on ControlEntryDetailsScreens

packages/apps/quality/src/hooks/use-quality-header-actions.ts, packages/apps/quality/src/i18n/en.json, packages/apps/quality/src/i18n/fr.json, packages/apps/quality/src/screens/index.js
=> fix: remove possibility to create control entry

packages/apps/quality/src/api/control-entry-api.js, packages/apps/quality/src/components/molecules/ControlEntryDetailsButtons/ControlEntryDetailsButtons.tsx, packages/apps/quality/src/features/controlEntrySlice.js, packages/apps/quality/src/screens/ControlEntryListScreen.js
=> fix: update ControlEntryList when controlEntry is updated

packages/apps/quality/src/screens/ControlEntryFormScreen.js
=> feat: handleNext on validation button and pop when is last validation

packages/core/src/components/organisms/DateInput/DateInput.tsx
=> fix: title props optional on DateInput

packages/apps/hr/src/index.ts
=> refactor: remove isDefault on active timer screen

packages/apps/quality/src/api/control-entry-api.js, packages/apps/quality/src/features/controlEntrySlice.js, packages/apps/quality/src/screens/ControlEntryListScreen.js, packages/apps/quality/src/types/controlEntry.tsx
=> feat: add status filter on list screen

packages/apps/crm/src/screens/event/EventPlanningScreen.js, packages/apps/crm/src/types/event-type.ts
=> feat: remove ToggleSwitch component and and enable props on planningView

packages/apps/crm/README.md, packages/apps/helpdesk/README.md, packages/apps/hr/README.md, packages/apps/manufacturing/README.md, packages/apps/quality/README.md, packages/apps/stock/README.md
=> chore: modify readme  of apps

packages/core/src/components/external/PlanningView/PlanningView.tsx, packages/ui/src/components/atoms/Switch/Switch.tsx, packages/ui/src/components/molecules/SwitchCard/SwitchCard.tsx
=> fix: size on button depends on device parameter

packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx, packages/apps/hr/src/components/atoms/index.js, packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx, packages/core/src/components/molecules/PeriodDisplay/PeriodDisplay.tsx, packages/core/src/components/molecules/index.js
=> feat: move component DatesInterval and rename it PeriodDisplay

packages/apps/quality/src/models/sortFields.ts
=> fix: inverse sort on list screen

packages/apps/helpdesk/src/screens/TicketFormScreen.js
=> fix: add reset action on create ticket form

packages/core/src/components/templates/MailMessageView/MailMessageView.js, packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
=>  fix: issue with keyboard in mailMessage

packages/core/src/header/HeaderActionsProvider.ts, packages/core/src/navigator/drawer/Header.js
=> fix: losing header actions after navigation

packages/core/src/components/pages/FormView/Components/Field.tsx
=> fix: display issue on required error in FormView

packages/apps/quality/src/api/control-entry-sample-line-api.js, packages/apps/quality/src/components/atoms/ControlEntryCard/ControlEntryCard.tsx, packages/apps/quality/src/components/molecules/ControlEntryFormButtons/ControlEntryFormButtons.tsx, packages/apps/quality/src/i18n/en.json, packages/apps/quality/src/i18n/fr.json, packages/apps/quality/src/screens/ControlEntryFormScreen.js, packages/apps/quality/src/types/controlEntry.tsx, packages/core/src/components/external/Toast/Toast.tsx, packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx
=> feat: add toast with sample result and fix refresh issues

changelogs/unreleased/75640.json, packages/apps/quality/src/screens/ControlEntryListScreen.js
=> fix: change success to primary color on ToggleButton

changelogs/unreleased/75492.json, packages/apps/crm/src/components/templates/CatalogsSearchBar/CatalogsSearchBar.js, packages/apps/crm/src/components/templates/ClientSearchBar/ClientSearchBar.js, packages/apps/crm/src/components/templates/ContactSearchBar/ContactSearchBar.js, packages/apps/crm/src/components/templates/LeadSearchBar/LeadSearchBar.js, packages/apps/crm/src/components/templates/OpportunitySearchBar/OpportunitySearchBar.js, packages/apps/crm/src/components/templates/ProspectSearchBar/ProspectSearchBar.js, packages/apps/crm/src/screens/catalog/CatalogListScreen.js, packages/apps/crm/src/screens/client/ClientsListScreen.js, packages/apps/crm/src/screens/contact/ContactListScreen.js, packages/apps/crm/src/screens/lead/LeadListScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js, packages/apps/crm/src/screens/prospect/ProspectsListScreen.js, packages/apps/helpdesk/src/components/templates/MyTeamTicketSearchBar/MyTeamTicketSearchBar.js, packages/apps/helpdesk/src/components/templates/MyTicketSearchBar/MyTicketSearchBar.js, packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js, packages/apps/helpdesk/src/screens/MyTicketListScreen.js
=> fix: search shows too many results on list screens (crm and helpdesk)

changelogs/unreleased/75624.json, packages/ui/__tests__/components/organisms/DistributionBar.test.js, packages/ui/src/components/organisms/DistributionBar/DistributionBar.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/DistributionBar.stories.tsx
=> feat: add DistributionBar component

changelogs/unreleased/75733.json, packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js, packages/apps/helpdesk/src/components/templates/CustomerSearchBar/CustomerSearchBar.js, packages/apps/helpdesk/src/components/templates/ProjectSearchBar/ProjectSearchBar.js, packages/apps/helpdesk/src/components/templates/TicketStopwatch/TicketStopwatch.js, packages/apps/helpdesk/src/features/customerSlice.js, packages/apps/helpdesk/src/features/index.js, packages/apps/helpdesk/src/features/projectSlice.js, packages/apps/helpdesk/src/features/timerSlice.js, packages/apps/hr/src/components/templates/ProductSearchBar/ProductSearchBar.tsx, packages/apps/hr/src/components/templates/ProjectSearchBar/ProjectSearchBar.tsx, packages/apps/hr/src/components/templates/ProjectTaskSearchBar/ProjectTaskSearchBar.tsx, packages/apps/hr/src/features/index.js, packages/apps/hr/src/features/projectSlice.js
=> fix: conflict reducer name 

packages/apps/stock/src/screens/loader/LoaderScreen.js, packages/core/src/components/templates/Loader/LoaderPopup.tsx, packages/core/src/components/templates/Loader/types.ts
=> feat: add props on Loader to force user to leave screen

changelogs/unreleased/75791_feat.json, changelogs/unreleased/75791_refactor.json, packages/core/src/app/ContextedApplication.tsx, packages/core/src/app/RootNavigator.js, packages/core/src/auth/screens/SettingsScreen.js, packages/core/src/features/authSlice.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/navigator/Navigator.js, packages/core/src/navigator/drawer/DrawerContent.js, packages/core/src/screens/LoginScreen.js, packages/core/src/screens/SessionManagementScreen.js
=> feat: add version on SettingsScreen

changelogs/unreleased/75762.json, packages/core/src/components/templates/SearchListScreen/SearchListScreen.tsx, packages/core/src/components/templates/SearchListView/SearchListView.tsx, packages/core/src/components/templates/index.js, packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
=> feat: creation of SearchListScreen to search and scroll

changelogs/unreleased/76103.json, changelogs/unreleased/76103_bis.json, packages/ui/__tests__/components/templates/BottomBar.test.js, packages/ui/src/components/molecules/NumberBubble/NumberBubble.tsx, packages/ui/src/components/templates/BottomBar/BarItem.tsx, packages/ui/src/components/templates/BottomBar/BottomBar.tsx, packages/ui/src/components/templates/BottomBar/display.helper.ts, packages/ui/src/components/templates/BottomBar/types.helper.ts, packages/ui/stories/templates/BottomBar.stories.tsx
=> feat: add BottomBar component

changelogs/unreleased/74584.json, packages/apps/hr/src/api/expense-line-api.js, packages/apps/hr/src/components/templates/ExpenseLineTypeDisplay/ExpenseLineTypeDisplay.tsx, packages/apps/hr/src/features/expenseLineSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
=> fix: use new request to update an ExpenseLine

changelogs/unreleased/75763.json, packages/core/src/screens/SessionManagementScreen.js, packages/core/src/sessions/components/display/SessionListCard.js
=> fix: improve display on login screen

packages/core/src/dashboards/component/AOPChart/AOPChart.tsx, packages/core/src/dashboards/view/DashboardScreen.tsx, packages/ui/src/components/templates/Dashboard/Dashboard.tsx
=> feat: add Aop chart on Dashboard

changelogs/unreleased/75937.json, packages/core/src/dashboards/view/DashboardScreen.tsx, packages/ui/src/components/templates/Dashboard/Chart/BarChart.tsx, packages/ui/src/components/templates/Dashboard/Chart/LineChart.tsx, packages/ui/src/components/templates/Dashboard/Dashboard.tsx
=> feat: add props to hide Card in Dashboard

packages/core/src/components/templates/SearchListView/SearchListView.tsx
=> refactor: add props to SearchListView

changelogs/unreleased/76105.json, jest/setup-mocks.js, packages/core/src/components/templates/AttachedFilesView/AttachedFilesView.js, packages/core/src/components/templates/MailMessageView/MailMessageView.js, packages/core/src/components/templates/SearchListView/SearchListView.tsx, packages/ui/__tests__/components/organisms/ScrollList.test.js, packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx, packages/ui/src/components/organisms/ScrollList/DottedButton.tsx, packages/ui/src/components/organisms/ScrollList/ScrollList.tsx, packages/ui/src/components/organisms/ScrollList/TopActions.tsx, packages/ui/src/components/organisms/ScrollList/index.ts, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/ScrollList.stories.tsx
=> feat: add actions on top of ScrollList

changelogs/unreleased/72197.json, packages/core/src/dashboards/view/DashboardScreen.tsx, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/ui/src/components/templates/Dashboard/Dashboard.tsx
=> feat: add last update date when refresh

changelogs/unreleased/77057.json, packages/ui/src/components/molecules/LabelText/LabelText.tsx
=> feat: add textSize props to LabelText component

packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/api/question-api.js, packages/apps/intervention/src/components/atoms/QuestionCard/QuestionCard.tsx, packages/apps/intervention/src/components/atoms/index.ts, packages/apps/intervention/src/components/molecules/InterventionHeader/InterventionHeader.tsx, packages/apps/intervention/src/components/pages/SurveyView/SurveyView.tsx, packages/apps/intervention/src/components/pages/index.ts, packages/apps/intervention/src/components/templates/SurveyRangeNavigation/SurveyRangeNavigation.tsx, packages/apps/intervention/src/components/templates/index.ts, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/index.js, packages/apps/intervention/src/features/questionSlice.js, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/models/objectFields.ts, packages/apps/intervention/src/models/sortFields.ts, packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx, packages/apps/intervention/src/types/index.ts, packages/apps/intervention/src/types/question.ts
=> feat: creation of SurveyView

packages/apps/intervention/src/api/intervention-api.js, packages/apps/intervention/src/components/atoms/InterventionCard/InterventionCard.tsx, packages/apps/intervention/src/components/molecules/InterventionDetailCard/InterventionDetailCard.tsx, packages/apps/intervention/src/components/pages/HistoryView/HistoryView.tsx, packages/apps/intervention/src/components/templates/InterventionsListView/InterventionsListView.tsx, packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx
=> feat: creation of HistoryView

packages/apps/intervention/src/api/equipment-line-api.js, packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/components/atoms/EquipmentLineCard/EquipmentLineCard.tsx, packages/apps/intervention/src/components/atoms/index.ts, packages/apps/intervention/src/components/molecules/EquipmentDetailsHeader/EquipmentDetailsHeader.tsx, packages/apps/intervention/src/components/molecules/EquipmentLineHeader/EquipmentLineHeader.tsx, packages/apps/intervention/src/components/molecules/index.ts, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/equipmentLineSlice.js, packages/apps/intervention/src/features/index.js, packages/apps/intervention/src/hooks/use-intervention-header-actions.ts, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/models/objectFields.ts, packages/apps/intervention/src/screens/equipment/EquipmentLineListScreen.tsx, packages/apps/intervention/src/screens/equipment/index.ts, packages/apps/intervention/src/types/equipment.tsx
=> feat: add equipmentLine Screen

changelogs/unreleased/73972.json, changelogs/unreleased/73972_admin.json, changelogs/unreleased/73972_form.json, packages/apps/crm/src/screens/catalog/CatalogListScreen.js, packages/core/src/auth/components/molecules/TranslationsButton/TranslationsButton.tsx, packages/core/src/auth/models/objectFields.ts, packages/core/src/auth/screens/UserScreen.js, packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx, packages/core/src/components/pages/FormView/Components/Field.tsx, packages/core/src/components/pages/FormView/FormView.tsx, packages/core/src/features/index.js, packages/core/src/features/metaJsonFieldSlice.js, packages/core/src/features/permissionSlice.js, packages/core/src/forms/studio/api.helpers.ts, packages/core/src/forms/studio/display.helpers.ts, packages/core/src/forms/studio/index.ts, packages/core/src/forms/studio/permission.helpers.ts, packages/core/src/forms/types.ts, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/index.ts, packages/core/src/models/objectFields.ts, packages/core/src/navigator/Navigator.js, packages/core/src/permissions/api.helpers.ts, packages/core/src/permissions/format.helpers.ts, packages/core/src/permissions/hooks.ts, packages/core/src/permissions/index.ts, packages/core/src/permissions/type.helpers.ts
=> feat: add hooks to manage user permissions

packages/ui/__tests__/components/organisms/ScrollList.test.js, packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
=> fix: display actions even when ScrollList data is empty

packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/api/intervention-api.js, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/interventionSlice.js, packages/apps/intervention/src/hooks/use-intervention-header-actions.ts, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/screens/equipment/EquipmentInterventionListScreen.tsx, packages/apps/intervention/src/screens/equipment/index.ts
=> feat: add EquipmentInterventionListScrren

packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/api/intervention-note-api.js, packages/apps/intervention/src/components/molecules/NoteDetailCard/NoteDetailCard.tsx, packages/apps/intervention/src/components/organisms/InterventionNoteTypePicker/InterventionNoteTypePicker.tsx, packages/apps/intervention/src/components/pages/NoteView/NoteView.tsx, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/interventionNoteSlice.js, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/models/forms.ts, packages/apps/intervention/src/models/objectFields.ts, packages/apps/intervention/src/models/sortFields.ts, packages/apps/intervention/src/screens/intervention/InterventionNoteFormScreen.tsx, packages/apps/intervention/src/screens/intervention/index.ts
=> feat: creation of NoteFormScreen

.storybook/main.js, jest/setup-mocks.js, packages/core/src/auth/screens/SettingsScreen.js, packages/ui/src/components/templates/BottomBar/BarItem.tsx, packages/ui/src/components/templates/BottomBar/BottomBar.tsx, packages/ui/stories/templates/BottomBar.stories.tsx
=> feat: add animation on scale button

changelogs/unreleased/77358.json, packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx, packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
=> fix: improve design of DropdownCard

changelogs/unreleased/77290.json, packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx, packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx, packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx, packages/apps/hr/src/components/atoms/index.js, packages/ui/__tests__/components/molecules/TextUnit.test.js, packages/ui/src/components/molecules/TextUnit/TextUnit.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/stories/molecules/TextUnit.stories.tsx
=> feat: move TextUnit to ui package

packages/apps/intervention/src/api/equipment-api.js, packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/components/atoms/EquipmentCard/EquipmentCard.tsx, packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx, packages/apps/intervention/src/components/molecules/InterventionHeader/InterventionHeader.tsx, packages/apps/intervention/src/components/organisms/EquipmentModeSwitch/EquipmentModeSwitch.tsx, packages/apps/intervention/src/components/organisms/index.ts, packages/apps/intervention/src/components/pages/EquipmentView/EquipmentView.tsx, packages/apps/intervention/src/components/pages/index.ts, packages/apps/intervention/src/components/templates/SurveyRangeNavigation/SurveyRangeNavigation.tsx, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/equipmentSlice.js, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/models/objectFields.ts, packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx, packages/apps/intervention/src/types/equipment.tsx
=> feat: creation of EquipmentView

changelogs/unreleased/76870.json, packages/apps/hr/src/models/forms.ts
=> fix: ignore error when user does not have an employee

packages/apps/intervention/src/components/pages/SurveyView/SurveyView.tsx, packages/apps/intervention/src/components/templates/SurveyRangeNavigation/SurveyRangeNavigation.tsx, packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx, packages/ui/src/components/organisms/Picker/Picker.tsx
=> feat: improve range management on survey view

changelogs/unreleased/77315.json, packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
=> fix: avoid error on SearchBar when no onChange function is provided

changelogs/unreleased/77314.json, packages/ui/__tests__/components/organisms/GridView.test.js, packages/ui/src/components/organisms/GridView/CellView.tsx, packages/ui/src/components/organisms/GridView/GridView.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/GridView.stories.tsx
=> feat: add new GridView component

changelogs/unreleased/74061.json, packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx
=> fix: enable limit with more than one digit

packages/apps/intervention/src/index.ts
=> feat: change icon of intervention module

changelogs/unreleased/77359.json, packages/ui/__tests__/components/organisms/DropdownCardSwitch.test.js, packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx, packages/ui/stories/organisms/DropdownCardSwitch.stories.tsx
=> feat: improve DropdownCardSwitch logic

changelogs/unreleased/75461_Dashboard.json, changelogs/unreleased/75641_Pickers.json, changelogs/unreleased/75641_UserScreen.json, packages/apps/stock/src/screens/auth/UserScreen.js, packages/core/src/auth/components/molecules/DashboardsCard/DashboardsCard.tsx, packages/core/src/auth/components/molecules/NavigationToolsButton/NavigationToolsButton.tsx, packages/core/src/auth/components/molecules/ShortcutsCard/ShortcutsCard.tsx, packages/core/src/auth/components/molecules/TranslationsButton/TranslationsButton.tsx, packages/core/src/auth/components/molecules/UserCard/UserCard.tsx, packages/core/src/auth/components/molecules/index.js, packages/core/src/auth/models/objectFields.ts, packages/core/src/auth/screens/SettingsScreen.js, packages/core/src/auth/screens/UserScreen.js, packages/core/src/dashboards/index.js, packages/core/src/dashboards/view/DashboardScreen.tsx, packages/core/src/dashboards/view/DashboardView.tsx, packages/core/src/dashboards/view/index.ts, packages/ui/src/components/templates/Dashboard/Dashboard.tsx
=> feat: improve user screen display

packages/core/src/auth/screens/UserScreen.js
=> feat: manage shortcut config on user screen

packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
=> fix:  add default value for currency

changelogs/unreleased/76223.json, packages/apps/manufacturing/src/api/manufacturing-order-api.js, packages/apps/manufacturing/src/api/operation-order-api.js, packages/apps/manufacturing/src/api/waste-product-api.js, packages/apps/manufacturing/src/models/searchFields.ts, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductListScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js, packages/core/src/components/templates/SearchListView/SearchListView.tsx
=> refactor: use SearchListView component on manufacturing

packages/ui/src/components/molecules/Alert/Alert.tsx
=> fix: add maxHeight on Alert component

changelogs/unreleased/73971.json, packages/core/src/auth/screens/SettingsScreen.js, packages/core/src/tools/LinkingProvider.ts, packages/core/src/tools/linking.helper.ts
=> feat: add openGoogleMapsDirections function

changelogs/unreleased/76224.json, packages/apps/stock/src/api/customer-delivery-api.js, packages/apps/stock/src/api/internal-move-api.js, packages/apps/stock/src/api/inventory-api.js, packages/apps/stock/src/api/stock-correction-api.js, packages/apps/stock/src/api/supplier-arrival-api.js, packages/apps/stock/src/features/stockCorrectionSlice.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js, packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js, packages/apps/stock/src/screens/inventories/InventoryListScreen.js, packages/apps/stock/src/screens/products/ProductListScreen.js, packages/apps/stock/src/screens/stockCorrections/StockCorrectionListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js, packages/apps/stock/src/types/stock-corrrection.tsx, packages/core/src/components/templates/SearchListView/SearchListView.tsx
=> refactor: use SearchListView component on stock

packages/apps/intervention/src/api/equipment-api.js, packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx, packages/apps/intervention/src/components/pages/EquipmentView/EquipmentView.tsx, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/equipmentSlice.js, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx, packages/apps/intervention/src/screens/equipment/EquipmentFormView.tsx
=> feat: add archive,copy and create APIs for equipments

packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/api/intervention-api.js, packages/apps/intervention/src/components/pages/GeneralInformationView/GeneralInformationView.tsx, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/interventionSlice.js, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json
=> feat: add API on intervention stopwatch

packages/apps/intervention/src/api/equipment-api.js, packages/apps/intervention/src/api/index.ts, packages/apps/intervention/src/api/intervention-api.js, packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx, packages/apps/intervention/src/components/pages/EquipmentView/EquipmentView.tsx, packages/apps/intervention/src/components/templates/LinkEquipmentPopup/LinkEquipmentPopup.tsx, packages/apps/intervention/src/components/templates/index.ts, packages/apps/intervention/src/features/asyncFunctions-index.ts, packages/apps/intervention/src/features/equipmentSlice.js, packages/apps/intervention/src/features/interventionSlice.js, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/screens/equipment/EquipmentFormView.tsx
=> feat: add link/unlink equipment functions

changelogs/unreleased/78020.json, packages/apps/crm/src/components/templates/ContactSearchBar/ContactSearchBar.tsx, packages/apps/crm/src/components/templates/LeadSearchBar/LeadSearchBar.tsx
=> fix: refresh issue on Event form view search bars

changelogs/unreleased/77825.json, packages/apps/stock/src/hooks/use-stock-header-actions.js, packages/apps/stock/src/screens/customerDeliveries/index.js, packages/apps/stock/src/screens/internalMoves/index.js, packages/apps/stock/src/screens/inventories/index.js, packages/apps/stock/src/screens/supplierArrivals/index.js
=> fix: add header action on line details stock screens

changelogs/unreleased/77940.json, packages/apps/crm/src/components/molecules/TourDetailsHeader/TourDetailsHeader.tsx, packages/apps/crm/src/components/organisms/TourItineraryButton/TourItineraryButton.tsx, packages/apps/crm/src/components/organisms/index.js, packages/apps/crm/src/screens/tour/TourDetailsScreen.js, packages/apps/crm/src/types/tourLine.tsx
=> feat: add new button to see itinerary on Tour details

changelogs/unreleased/74084.json, packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationAlert/InternalMoveCreationAlert.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationButtons/InternalMoveCreationButtons.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationViewAll/InternalMoveCreationViewAll.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationViewAll/LineComponent.tsx, packages/apps/stock/src/screens/internalMoves/InternalMoveCreationScreen.js
=> feat: enable edit mode when creating an internal move

changelogs/unreleased/77769.json, packages/core/src/navigator/drawer/DrawerContent.js, packages/core/src/navigator/drawer/Menu.js, packages/core/src/navigator/drawer/MenuTitle.js
=> fix: add scrollview on drawer to manage small screen

changelogs/unreleased/78039.json, packages/core/src/components/external/WebView/WebView.tsx, packages/core/src/features/index.js, packages/core/src/features/mobileWebViewSlice.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/navigator/Navigator.js, packages/core/src/navigator/menu.helper.js, packages/core/src/webViews/api.helpers.ts, packages/core/src/webViews/display.helpers.ts, packages/core/src/webViews/menu.helper.ts, packages/core/src/webViews/view/WebViewScreen.tsx, packages/core/src/webViews/view/index.ts, src/app.config.js
=> feat: create menu entries for Webview with web config

changelogs/unreleased/78018.json, packages/apps/crm/src/types/event-type.ts
=> fix: translation in Event getStatusList function

changelogs/unreleased/77717.json, packages/ui/src/components/atoms/BootstrapIcon/BootstrapIcon.tsx
=> fix: question mark when dark mode

changelogs/unreleased/78311.json, packages/apps/crm/src/components/organisms/Opportunity/OpportunityDropdownInfo/OpportunityDropdownInfo.js
=> fix: width issue on dropdown on opportunity details screen

packages/apps/intervention/src/features/equipmentSlice.js, packages/apps/intervention/src/hooks/use-intervention-header-actions.ts, packages/apps/intervention/src/screens/equipment/EquipmentFormView.tsx
=> fix: hide header actions on equipment creation

changelogs/unreleased/78337.json, packages/apps/hr/src/api/timer-api.js, packages/apps/hr/src/models/sortFields.ts
=> fix: inconsistency issues on Timers list view

changelogs/unreleased/77949.json, packages/apps/intervention/src/components/organisms/ContractSearchBar/ContractSearchBar.tsx, packages/apps/intervention/src/components/organisms/EquipmentFamilySearchBar/EquipmentFamilySearchBar.tsx, packages/apps/intervention/src/hooks/use-intervention-header-actions.ts, packages/apps/intervention/src/models/forms.ts
=> fix: hide field depending on equipment type

changelogs/unreleased/77872.json, packages/apps/crm/src/screens/catalog/CatalogListScreen.js, packages/apps/crm/src/screens/client/ClientsListScreen.js, packages/apps/crm/src/screens/contact/ContactListScreen.js, packages/apps/crm/src/screens/lead/LeadListScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js, packages/apps/crm/src/screens/prospect/ProspectsListScreen.js, packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductListScreen.js
=> fix: remove useless onChangeSearchValue

changelogs/unreleased/77952.json, packages/ui/__tests__/components/organisms/TagList.test.js, packages/ui/src/components/organisms/TagList/TagList.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/TagList.stories.tsx
=> feat: add TagList to display list of tags

packages/apps/intervention/src/index.ts
=> fix:  remove comptability comments in intervention config

packages/apps/intervention/src/screens/intervention/ActiveInterventionScreen.tsx, packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx
=> fix: refresh issue on active intervention screen

changelogs/unreleased/78348.json, packages/core/src/sessions/components/alerts/PopupCreateSession.js, packages/core/src/sessions/components/alerts/PopupEditSession.js, packages/core/src/sessions/components/alerts/PopupSession.js, packages/core/src/sessions/components/inputs/SessionInputs.js, packages/core/src/sessions/components/inputs/UrlInput.js, packages/core/src/sessions/components/inputs/UsernameInput.js
=> fix: max height issue on login popup

package.json
=> feat: update maxParallel to include project module to yarn dev

packages/apps/intervention/src/components/pages/SurveyView/SurveyView.tsx, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/screens/intervention/InterventionQuestionFormScreen.tsx, packages/apps/intervention/src/types/question.ts
=> feat: add question status on form view

changelogs/unreleased/78441.json, packages/apps/hr/src/api/project-api.js, packages/apps/hr/src/components/templates/ProjectTaskSearchBar/ProjectTaskSearchBar.tsx, packages/apps/hr/src/models/forms.ts
=> fix: modify filters on timesheet lines and timers

packages/core/src/auth/screens/SettingsScreen.js
=> fix: crash when change language

changelogs/unreleased/78347.json, packages/apps/stock/src/components/templates/supplierArrival/SupplierProductInfo/SupplierProductInfo.js
=> fix: display issue on supplier arrival line details view

packages/apps/intervention/src/screens/intervention/ActiveInterventionScreen.tsx
=> fix: error when going an active intervention screen after loading the app

changelogs/unreleased/78631.json, packages/core/src/sessions/components/inputs/PasswordInput.js
=> fix: reverse icon password order

packages/apps/intervention/src/components/atoms/QuestionCard/QuestionCard.tsx, packages/apps/intervention/src/i18n/en.json, packages/apps/intervention/src/i18n/fr.json, packages/apps/intervention/src/screens/intervention/InterventionQuestionFormScreen.tsx
=> feat: add InfoBubble on QuestionCard

changelogs/unreleased/77755.json, packages/apps/crm/src/api/index.ts, packages/apps/crm/src/api/tour-line-api.js, packages/apps/crm/src/components/organisms/TourLineActionCard/TourLineActionCard.tsx, packages/apps/crm/src/components/organisms/TourLineEventPopup/TourLineEventPopup.tsx, packages/apps/crm/src/components/organisms/index.js, packages/apps/crm/src/components/templates/EventPartnerPicker/EventPartnerPicker.tsx, packages/apps/crm/src/components/templates/index.js, packages/apps/crm/src/features/asyncFunctions-index.ts, packages/apps/crm/src/features/eventSlice.js, packages/apps/crm/src/features/tourLineSlice.js, packages/apps/crm/src/i18n/en.json, packages/apps/crm/src/i18n/fr.json, packages/apps/crm/src/screens/event/EventFormScreen.js, packages/apps/crm/src/screens/tour/TourDetailsScreen.js
=> feat: add possibility to create a new event from a tour line

packages/apps/intervention/src/hooks/use-intervention-header-actions.ts, packages/apps/intervention/src/screens/intervention/index.ts
=> fix: add header actions in active intervention screen

changelogs/unreleased/78043.json, packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx, packages/core/src/forms/studio/formula.helpers.ts
=> fix: custom field form do not consider value when field type does not contain attrs

changelogs/unreleased/78691.json, packages/apps/manufacturing/src/api/manufacturing-order-api.js, packages/apps/manufacturing/src/api/operation-order-api.js, packages/apps/manufacturing/src/components/molecules/ManufacturingOrderDatesCard/ManufacturingOrderDatesCard.tsx, packages/apps/manufacturing/src/components/molecules/OperationOrderDatesCard/OperationOrderDatesCard.tsx, packages/apps/manufacturing/src/components/organisms/LinkedManufacturingOrderCard/LinkedManufacturingOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/ManufacturingOrderButtons/ManufacturingOrderButtons.js, packages/apps/manufacturing/src/components/organisms/ManufacturingOrderCard/ManufacturingOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/ManufacturingOrderHeader/ManufacturingOrderHeader.tsx, packages/apps/manufacturing/src/components/organisms/OperationOrderCard/OperationOrderCard.tsx, packages/apps/manufacturing/src/components/organisms/OperationOrderDetailsCard/OperationOrderDetailsCard.tsx, packages/apps/manufacturing/src/components/organisms/OperationOrderHeader/OperationOrderHeader.tsx, packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js, packages/apps/manufacturing/src/index.ts, packages/apps/manufacturing/src/models/index.ts, packages/apps/manufacturing/src/models/typeObjects.ts, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderOperationListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ChildrenManufOrderListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductListScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductListScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderPlanningScreen.js, packages/apps/manufacturing/src/types/manufacturing-order.tsx, packages/apps/manufacturing/src/types/operation-order.tsx, packages/apps/manufacturing/src/utils/dates.ts
=> feat: use new selections system on manufacturing

changelogs/unreleased/78689.json, packages/apps/helpdesk/src/components/molecules/TicketCard/TicketCard.tsx, packages/apps/helpdesk/src/components/templates/TicketHeader/TicketHeader.js, packages/apps/helpdesk/src/components/templates/TicketPriorityPicker/TicketPriorityPicker.js, packages/apps/helpdesk/src/index.ts, packages/apps/helpdesk/src/models/index.ts, packages/apps/helpdesk/src/models/typeObjects.ts, packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js, packages/apps/helpdesk/src/screens/MyTicketListScreen.js, packages/apps/helpdesk/src/types/ticket.tsx
=> refactor: use new selections system on helpdesk

changelogs/unreleased/78687.json, packages/apps/hr/src/api/expense-api.js, packages/apps/hr/src/api/timer-api.js, packages/apps/hr/src/api/timesheet-api.js, packages/apps/hr/src/components/atoms/ExpenseCard/ExpenseCard.tsx, packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx, packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx, packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx, packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx, packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx, packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx, packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx, packages/apps/hr/src/components/templates/ExpenseHeader/ExpenseHeader.tsx, packages/apps/hr/src/components/templates/ExpenseLineSwitchAdd/ExpenseLineSwitchAdd.tsx, packages/apps/hr/src/components/templates/KilometricTypeSelectPicker/KilometricTypeSelectPicker.js, packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx, packages/apps/hr/src/components/templates/TimesheetFilters/TimesheetFilters.js, packages/apps/hr/src/index.ts, packages/apps/hr/src/models/forms.ts, packages/apps/hr/src/models/index.ts, packages/apps/hr/src/models/typeObjects.ts, packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js, packages/apps/hr/src/screens/expense/ExpenseListScreen.js, packages/apps/hr/src/screens/timesheet/TimerListScreen.js, packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js, packages/apps/hr/src/types/expense.tsx, packages/apps/hr/src/types/expenseLine.tsx, packages/apps/hr/src/types/time.ts, packages/apps/hr/src/types/timesheet.ts
=> refactor: use new selections system on hr

changelogs/unreleased/79177.json, packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js
=> fix: disable stop button when timer is paused

changelogs/unreleased/78932.json, packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js
=> fix: in progress chip displayed in two lines

changelogs/unreleased/79224.json, packages/core/src/components/pages/FormView/Components/Field.tsx
=> fix: date input crash after emptying

changelogs/unreleased/78692.json, packages/apps/quality/src/api/control-entry-sample-line-api.js, packages/apps/quality/src/components/atoms/ControlEntryCard/ControlEntryCard.tsx, packages/apps/quality/src/components/atoms/ControlEntryHeader/ControlEntryHeader.tsx, packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx, packages/apps/quality/src/components/atoms/ControlEntrySampleLineHeader/ControlEntrySampleLineHeader.tsx, packages/apps/quality/src/components/molecules/ControlEntryDetailsButtons/ControlEntryDetailsButtons.tsx, packages/apps/quality/src/components/molecules/ControlEntryDetailsHeader/ControlEntryDetailsHeader.tsx, packages/apps/quality/src/components/molecules/ControlEntryFormButtons/ControlEntryFormButtons.tsx, packages/apps/quality/src/index.ts, packages/apps/quality/src/models/index.ts, packages/apps/quality/src/models/typeObjects.ts, packages/apps/quality/src/screens/ControlEntryDetailsScreen.js, packages/apps/quality/src/screens/ControlEntryFormScreen.js, packages/apps/quality/src/screens/ControlEntryListScreen.js, packages/apps/quality/src/types/controlEntry.tsx
=> refactor: use new selections system on quality

changelogs/unreleased/79211.json, packages/ui/src/components/molecules/Increment/Increment.tsx
=> fix: increment input issue when null value

packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/ui/__tests__/components/organisms/TagList.test.js, packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx, packages/ui/src/components/organisms/TagList/TagList.tsx, packages/ui/stories/organisms/TagList.stories.tsx
=> feat: display message when no data in TagList

changelogs/unreleased/75768.json, packages/ui/__tests__/components/organisms/ScrollList.test.js, packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
=> refactor: remove loading on ScrollList

changelogs/unreleased/79535.json, packages/apps/hr/src/features/expenseLineSlice.js
=> fix: infinite loading after deleting an expense line

changelogs/unreleased/79670.json, packages/core/src/components/organisms/HeaderBandList/HeaderBandList.tsx
=> fix: on iOS HeaderBandList is on the status bar

packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
=> fix: Contact DropdownCard cannot be open in ContactDetailsScreen

changelogs/unreleased/79427.json, packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
=> fix: refresh issue on NotesCard component

changelogs/unreleased/75625.json, packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx, packages/apps/quality/src/components/molecules/ControlEntryDetailsHeader/ControlEntryDetailsHeader.tsx, packages/apps/quality/src/components/molecules/FillingMethodAlert/FillingMethodAlert.tsx, packages/apps/quality/src/screens/ControlEntryDetailsScreen.js, packages/apps/quality/src/screens/ControlEntryFormScreen.js
=> feat: enable selection of a specific sample from detail list

packages/core/src/selections/types.ts
=> fix: make selectedItem not required on getCustomSelectionItems

changelogs/unreleased/79421.json, packages/core/src/apiProviders/Standard/requests.helper.ts, packages/core/src/apiProviders/utils.ts, packages/core/src/auth/components/molecules/UserCard/UserCard.tsx, packages/core/src/auth/screens/UserScreen.js, packages/ui/__tests__/components/organisms/AutoCompleteSearch.test.js, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/SearchDetailsPopUp.tsx
=> refactor: improve management of pages

packages/core/src/permissions/api.helpers.ts
=> refactor: use AOS request for user permissions

changelogs/unreleased/79175.json, packages/apps/intervention/src/api/equipment-api.js, packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx, packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx, packages/core/src/components/templates/index.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/ui/src/components/templates/TreeView/Branch.tsx, packages/ui/src/components/templates/TreeView/BranchCard.tsx, packages/ui/src/components/templates/TreeView/TreeView.tsx
=> feat: create SearchTreeView component and use it in CustomerParkScreen

packages/apps/sales/src/components/atoms/StateBadge/StateBadge.tsx, packages/apps/sales/src/components/atoms/index.ts, packages/apps/sales/src/components/index.ts, packages/apps/sales/src/i18n/en.json, packages/apps/sales/src/i18n/fr.json
=> feat: creation of new component StateBadge

changelogs/unreleased/80359.json, packages/core/src/auth/screens/UserScreen.js, packages/ui/src/config/ConfigContext.tsx, packages/ui/src/hooks/use-price-format.ts
=> feat: add format helper for price digits

packages/apps/hr/src/components/molecules/TimerStopwatch/TimerStopwatch.tsx, packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx, packages/apps/hr/src/features/timerSlice.js, packages/apps/hr/src/hooks/use-hr-header-actions.js, packages/apps/hr/src/index.ts, packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
=> fix: manage when multiple timer is not enable

changelogs/unreleased/80585.json, packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx, packages/core/src/components/pages/FormView/FormView.tsx
=> fix: padding issue on CustomFieldForm

changelogs/unreleased/80506.json, packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
=> fix: MultiValuePicker Item type

changelogs/unreleased/80416.json, packages/core/src/navigator/module.helper.ts
=> feat: use new logic for authorized menus

packages/apps/project/src/api/index.ts, packages/apps/project/src/api/project-api.js, packages/apps/project/src/components/atoms/ProjectCard/ProjectCard.tsx, packages/apps/project/src/components/pages/SubProjectView/SubProjectView.tsx, packages/apps/project/src/components/pages/index.ts, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/projectSlice.js, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json, packages/apps/project/src/models/objectFields.ts, packages/apps/project/src/screens/ProjectDetailsScreen.tsx
=> feat: add SubProjectView in Project module

changelogs/unreleased/80843.json, packages/core/src/components/templates/SearchListView/SearchListView.tsx
=> fix: typing issue on SearchListView

packages/apps/sales/src/api/index.ts, packages/apps/sales/src/api/sale-order-line-api.js, packages/apps/sales/src/components/atoms/SaleOrderLineCard/SaleOrderLineCard.tsx, packages/apps/sales/src/components/atoms/SaleOrderSeeLinesButton/SaleOrderSeeLinesButton.tsx, packages/apps/sales/src/components/atoms/index.ts, packages/apps/sales/src/components/molecules/SaleOrderPriceDetails/SaleOrderPriceDetails.tsx, packages/apps/sales/src/features/asyncFunctions-index.ts, packages/apps/sales/src/features/index.js, packages/apps/sales/src/features/saleOrderLineSlice.js, packages/apps/sales/src/i18n/en.json, packages/apps/sales/src/i18n/fr.json, packages/apps/sales/src/models/objectFields.ts, packages/apps/sales/src/models/sortFields.ts, packages/apps/sales/src/models/typeObjects.ts, packages/apps/sales/src/screens/saleOrder/SaleOrderDetailsScreen.tsx, packages/apps/sales/src/screens/saleOrder/SaleOrderLineListScreen.tsx, packages/apps/sales/src/screens/saleOrder/index.ts
=> feat: create SaleOrderLine list screen

packages/apps/sales/src/index.ts, packages/apps/sales/src/screens/saleOrder/SaleOrdersScreen.tsx, packages/apps/sales/src/screens/saleOrder/SaleQuotationsScreen.tsx, packages/apps/sales/src/screens/saleOrder/index.ts
=> fix: rename screen components

changelogs/unreleased/80812.json, packages/ui/src/components/organisms/ProgressBar/ProgressBar.tsx
=> fix: display issue on ProgressBar when progress is very low

changelogs/unreleased/71032_scanner.json, changelogs/unreleased/71032_searchFocus.json, packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx, packages/core/src/components/templates/SearchListView/SearchListView.tsx
=> fix: clear scanner value after use

patches/react-native-blob-util+0.17.3.patch, patches/react-native-datawedge-intents+0.1.8.patch, patches/react-native-device-info+10.14.0.patch
=> chore: patch packages for sdk 34

changelogs/unreleased/80956.json, packages/ui/src/components/templates/BottomBar/BottomBar.tsx
=> fix: BottomBar is cut on iOS due to HeaderBand fix

changelogs/unreleased/80726.json, changelogs/unreleased/80726_timer.json, packages/apps/intervention/src/components/pages/GeneralInformationView/GeneralInformationView.tsx, packages/core/src/components/external/Timer/Timer.tsx
=> fix: manage small screens on intervention

changelogs/unreleased/80717.json, changelogs/unreleased/80717_header.json, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderDetailsScreen.js, packages/core/src/navigator/drawer/Header.js
=> fix: manage long title header and scrollView in OperationOrderDetailsScreen

changelogs/unreleased/81081.json, packages/core/src/app/context.helper.ts
=> fix: issue when merging configuration

packages/apps/sales/src/api/customer-api.js, packages/apps/sales/src/api/index.ts, packages/apps/sales/src/components/atoms/ClientCard/ClientCard.tsx, packages/apps/sales/src/components/atoms/index.ts, packages/apps/sales/src/components/molecules/ClientActionCard/ClientActionCard.tsx, packages/apps/sales/src/components/molecules/index.ts, packages/apps/sales/src/components/organisms/CategorySearchBar/CategorySearchBar.tsx, packages/apps/sales/src/features/asyncFunctions-index.ts, packages/apps/sales/src/features/customerSlice.js, packages/apps/sales/src/i18n/en.json, packages/apps/sales/src/i18n/fr.json, packages/apps/sales/src/index.ts, packages/apps/sales/src/models/objectFields.ts, packages/apps/sales/src/models/searchFields.ts, packages/apps/sales/src/models/sortFields.ts, packages/apps/sales/src/screens/client/ClientListScreen.tsx, packages/apps/sales/src/screens/client/index.ts
=> feat: create clients list screen

changelogs/unreleased/80710.json, packages/core/src/selections/SelectionProvider.tsx, packages/core/src/selections/format.helpers.ts, packages/core/src/selections/hooks.ts
=> fix: refresh issue in useTypes function

packages/apps/sale/src/components/molecules/SaleOrderHeader/SaleOrderHeader.tsx
=> feat: add order edited icon, delivery and invoicing badges on SaleOrder details

changelogs/unreleased/81306.json, packages/apps/hr/src/screens/expense/ExpenseLinesListScreen.js
=> fix: wrong content when opening selection mode from header

changelogs/unreleased/81300.json, packages/apps/hr/src/models/forms.ts, packages/apps/hr/src/utils/employee.ts, packages/apps/hr/src/utils/index.ts
=> fix: do not hide field when imputation field is null

changelogs/unreleased/81324_header.json, changelogs/unreleased/81324_type.json, packages/apps/hr/src/api/timer-api.js, packages/apps/hr/src/hooks/use-hr-header-actions.js, packages/apps/hr/src/models/typeObjects.ts, packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js, packages/apps/hr/src/screens/expense/index.js, packages/apps/hr/src/screens/timesheet/TimerFormScreen.js, packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js, packages/apps/hr/src/screens/timesheet/index.ts
=> fix: add header actions of hr screens

changelogs/unreleased/81364.json, packages/core/src/forms/studio/display.helpers.ts
=> feat: manage drawing widget on custom form

packages/apps/sale/src/api/complementary-product-api.js, packages/apps/sale/src/api/index.ts, packages/apps/sale/src/components/atoms/ComplementaryProductCard/ComplementaryProductCard.tsx, packages/apps/sale/src/components/atoms/index.ts, packages/apps/sale/src/components/molecules/ProductFloatingButton/ProductFloatingButton.tsx, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/complementaryProductSlice.js, packages/apps/sale/src/features/index.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/models/objectFields.ts, packages/apps/sale/src/models/searchFields.ts, packages/apps/sale/src/models/sortFields.ts, packages/apps/sale/src/screens/product/ComplementaryProductsScreen.tsx, packages/apps/sale/src/screens/product/index.ts
=> feat: create complementary products screen

changelogs/unreleased/80369.json, packages/apps/sale/src/api/index.ts, packages/apps/sale/src/api/price-list-line-api.js, packages/apps/sale/src/components/atoms/PriceListCard/PriceListCard.tsx, packages/apps/sale/src/components/atoms/index.ts, packages/apps/sale/src/components/molecules/ProductFloatingButton/ProductFloatingButton.tsx, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/index.js, packages/apps/sale/src/features/priceListLineSlice.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/models/objectFields.ts, packages/apps/sale/src/models/searchFields.ts, packages/apps/sale/src/models/sortFields.ts, packages/apps/sale/src/models/typeObjects.ts, packages/apps/sale/src/screens/product/ProductSalePriceListsScreen.tsx, packages/apps/sale/src/screens/product/index.ts, packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
=> feat: create product price lists screen

changelogs/unreleased/70291.json, packages/core/src/app/Application.tsx, packages/core/src/sessions/SessionStorage.ts, src/app.config.js
=> feat: add default session for demo app

changelogs/unreleased/75975.json, packages/apps/manufacturing/src/i18n/en.json, packages/apps/manufacturing/src/i18n/fr.json, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
=> fix: trad in manufacturing order

changelogs/unreleased/81223.json, packages/core/src/components/organisms/MailMessageNotificationCard/MailMessageNotificationCard.tsx
=> fix: make props not required in MailMessageNotificationCard

changelogs/unreleased/80714.json, packages/apps/stock/src/components/templates/product/ProductSeeStockLocationDistribution/ProductSeeStockLocationDistribution.js
=> fix: margin issue when smallscreen

changelogs/unreleased/81199.json, packages/ui/__tests__/components/molecules/MultiValuePickerButton.test.js, packages/ui/__tests__/components/organisms/MultiValuePicker.test.js, packages/ui/__tests__/components/organisms/Picker.test.js, packages/ui/src/components/molecules/MultiValuePickerButton/MultiValuePickerButton.tsx, packages/ui/src/components/molecules/RightIconButton/RightIconButton.tsx, packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx, packages/ui/src/components/organisms/Picker/Picker.tsx, packages/ui/stories/organisms/MultiValuePicker.stories.tsx, packages/ui/stories/organisms/Picker.stories.tsx
=> feat: add placeholder on picker

changelogs/unreleased/81627.json, packages/apps/hr/src/models/forms.ts
=> fix: add null check on mobileSettings in hr form conditions

changelogs/unreleased/81256.json, changelogs/unreleased/81256_buttons.json, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/ui/__tests__/components/organisms/ActionCard.test.js, packages/ui/src/components/molecules/CardIconButton/CardIconButton.tsx, packages/ui/src/components/organisms/ActionCard/ActionCard.tsx, packages/ui/src/components/organisms/InfoButton/InfoButton.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/ActionCard.stories.tsx
=> feat: create new component ActionCard

changelogs/unreleased/81739.json, packages/core/src/components/pages/FormView/FormView.tsx, packages/core/src/screens/JsonFieldScreen.tsx
=> fix: remove bottom buttons on CustomFieldForm

packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx
=> fix: display issue on TaskCard

packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx
=> feat: improve TaskCard

packages/apps/manufacturing/src/components/organisms/ConsumedProductGlobalCard/ConsumedProductGlobalCard.tsx, packages/ui/src/components/organisms/ActionCard/ActionCard.tsx
=> feat: add props ActionCard to force actions display

changelogs/unreleased/73774.json, packages/ui/__tests__/components/organisms/GroupByScrollList.test.js, packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx, packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
=> feat: always leave information of current group on GroupByScrollList

changelogs/unreleased/81791.json, packages/apps/intervention/src/components/atoms/EquipmentCard/EquipmentCard.tsx, packages/apps/intervention/src/components/atoms/InterventionCard/InterventionCard.tsx, packages/apps/intervention/src/components/atoms/NoteCard/NoteCard.tsx, packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx, packages/apps/intervention/src/components/molecules/InterventionDetailCard/InterventionDetailCard.tsx, packages/apps/intervention/src/components/molecules/NoteDetailCard/NoteDetailCard.tsx
=> feat: replace cards with actions by ActionCard in intervention

packages/apps/project/src/components/molecules/ProjectHeader/ProjectHeader.tsx
=> fix: issue when title to long on project header

packages/apps/project/src/components/atoms/PartnerCard/PartnerCard.tsx, packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx, packages/apps/project/src/components/molecules/PartnerActionCard/PartnerActionCard.tsx, packages/apps/project/src/components/molecules/TaskActionCard/TaskActionCard.tsx, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json
=> refactor: use Action ActionCard Project

packages/ui/src/components/templates/Dashboard/Chart/IndicatorChart/IndicatorChart.tsx
=> fix: Indicator datasets type

changelogs/unreleased/78046.json, packages/core/src/api/print-template-api.js, packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js, packages/core/src/components/organisms/PopupPrintTemplate/PopupPrintTemplate.tsx, packages/core/src/components/organisms/index.js, packages/core/src/components/templates/PrintTemplateSearchBar/PrintTemplateSearchBar.tsx, packages/core/src/components/templates/index.js, packages/core/src/features/index.js, packages/core/src/features/printTemplateSlice.js, packages/core/src/header/hooks.js, packages/core/src/header/types.ts, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/models/objectFields.ts, packages/core/src/models/searchFields.ts, packages/core/src/navigator/drawer/Header.js, packages/core/src/tools/FileViewer.ts
=> feat: add print template

packages/apps/sale/src/components/atoms/ClientCard/ClientCard.tsx, packages/apps/sale/src/components/atoms/PartnerCard/PartnerCard.tsx, packages/apps/sale/src/components/molecules/ClientActionCard/ClientActionCard.tsx, packages/apps/sale/src/components/molecules/PartnerActionCard/PartnerActionCard.tsx, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json
=> refactor: use Action Card on Sales module

packages/apps/sale/src/index.ts
=> fix: modify menu icon of products

changelogs/unreleased/80721.json, packages/apps/crm/src/screens/client/ClientDetailsScreen.js, packages/apps/crm/src/screens/contact/ContactDetailsScreen.js, packages/apps/crm/src/screens/lead/LeadDetailsScreen.js, packages/apps/crm/src/screens/opportunity/OpportunityDetailsScreen.js, packages/apps/crm/src/screens/prospect/ProspectDetailsScreen.js
=> fix: add scrollview style to enable scrollview for CRM

changelogs/unreleased/82727.json, packages/apps/stock/src/hooks/use-stock-header-actions.js, packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js
=> fix: null issue on product details

changelogs/unreleased/80402.json, packages/ui/src/components/templates/Dashboard/Chart/ChartRender.tsx, packages/ui/src/components/templates/Dashboard/chart-type.ts
=> feat: add Indicator chart in ChartRender

changelogs/unreleased/80473.json, packages/apps/sale/src/screens/product/ProductSalePriceListsScreen.tsx, packages/core/src/components/templates/PeriodInput/PeriodInput.tsx, packages/core/src/utils/index.ts, packages/core/src/utils/time.js
=> feat: add default interval on period Input

changelogs/unreleased/82748.json, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
=> feat: add a more results indicator on search bar

packages/core/src/app/ContextsProvider.tsx, packages/core/src/loader/ProcessProvider.ts, packages/core/src/loader/ProcessStorage.ts, packages/core/src/screens/index.js
=> feat: clean process storage to keep only recent calls

changelogs/unreleased/80472.json, packages/apps/manufacturing/src/api/prod-product-api.js, packages/apps/manufacturing/src/components/organisms/ConsumedProductCard/ConsumedProductCard.tsx, packages/apps/manufacturing/src/components/organisms/ConsumedProductGlobalCard/ConsumedProductGlobalCard.tsx, packages/apps/manufacturing/src/components/organisms/ManufacturingOrderHeader/ManufacturingOrderHeader.tsx, packages/apps/manufacturing/src/models/objectFields.ts, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
=> feat: add a badge to get information about linked StockMove status on consumed products

changelogs/unreleased/83138.json, packages/ui/stories/templates/TreeView.stories.tsx
=> feat: add story for TreeView

packages/apps/project/src/api/index.ts, packages/apps/project/src/api/reporting-api.js, packages/apps/project/src/components/pages/ReportingView/ReportingView.tsx, packages/apps/project/src/components/pages/TimeView/TimeView.tsx, packages/apps/project/src/components/templates/ReportingDetailsView/IndicatorCategory.tsx, packages/apps/project/src/components/templates/ReportingDetailsView/ReportingDetailsView.tsx, packages/apps/project/src/components/templates/index.ts, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/index.js, packages/apps/project/src/features/reportingSlice.js, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json, packages/ui/src/components/templates/Dashboard/Chart/IndicatorChart/IndicatorChart.tsx
=> feat: reporting tab on project details

packages/ui/stories/templates/Dashboard/IndicatorChart.stories.tsx
=> feat: add IndicatorChart stories

changelogs/unreleased/75800.json, packages/core/src/auth/screens/UserScreen.js, packages/ui/src/components/atoms/ScrollView/ScrollView.tsx, packages/ui/src/components/organisms/DraggableWrapper/DraggableWrapper.tsx, packages/ui/src/components/organisms/ScrollList/ScrollList.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/src/config/ConfigContext.tsx, packages/ui/stories/organisms/DraggableWrapper.stories.tsx
=> feat: add DraggableWrapper component

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/api/leave-api.js, packages/apps/hr/src/components/atoms/LeaveCard/LeaveCard.tsx, packages/apps/hr/src/components/atoms/index.js, packages/apps/hr/src/components/molecules/LeaveActionCard/LeaveActionCard.tsx, packages/apps/hr/src/components/molecules/index.js, packages/apps/hr/src/components/templates/LeaveFilters/LeaveFilters.tsx, packages/apps/hr/src/components/templates/LeaveWaitingValidationSearchBar/LeaveWaitingValidationSearchBar.tsx, packages/apps/hr/src/components/templates/index.js, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/index.js, packages/apps/hr/src/features/leaveSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/index.ts, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/models/searchFields.ts, packages/apps/hr/src/models/typeObjects.ts, packages/apps/hr/src/screens/leaveRequests/LeaveListScreen.tsx, packages/apps/hr/src/screens/leaveRequests/index.ts, packages/apps/hr/src/types/index.ts, packages/apps/hr/src/types/leave.ts
=> feat: add leave list view

packages/apps/project/src/screens/TaskFormScreen.tsx
=> refactor: default edit mode on Task

changelogs/83264.json, packages/ui/src/components/organisms/ProgressBar/ProgressBar.tsx
=> refactor: show minimum value on ProgressBar

packages/apps/project/src/components/templates/ActivityListView/ActivityListView.tsx, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json
=> refactor: add message when no activities

changelogs/unreleased/83389.json, packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductDetailsScreen.js, packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductDetailsScreen.js, packages/apps/stock/src/components/organisms/index.js, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationQuantityCard/InternalMoveCreationQuantityCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineQuantityCard/InternalMoveLineQuantityCard.js, packages/apps/stock/src/components/templates/inventory/InventoryLineQuantityCard/InventoryLineQuantityCard.tsx, packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionQuantityCard/StockCorrectionQuantityCard.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalAddTrackingScreen.js, packages/ui/__tests__/components/organisms/QuantityCard.test.js, packages/ui/src/components/organisms/QuantityCard/QuantityCard.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/QuantityCard.stories.tsx
=> feat: move QuantityCard to ui

packages/apps/project/src/components/templates/ActivityListView/ActivityListView.tsx
=> fix: refresh issue

changelogs/unreleased/83949.json, packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx
=> fix: border radius of content drodown card

packages/apps/sale/src/components/atoms/SaleOrderLineCard/SaleOrderLineCard.tsx, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json
=> fix: improve sale order line card

changelogs/unreleased/83831.json, packages/apps/hr/src/index.ts
=> fix: hide timer depends on config

packages/apps/sale/src/components/atoms/ComplementaryProductCard/ComplementaryProductCard.tsx
=> feat: add copy to clipboard on ComplementaryPriductCard

changelogs/unreleased/83801.json, packages/ui/src/components/templates/BottomBar/BottomBar.tsx, packages/ui/src/components/templates/BottomBar/types.helper.ts
=> feat: add new Item type for bottom bar

packages/apps/project/src/components/templates/ProjectListView/ProjectListView.tsx, packages/apps/project/src/components/templates/TaskFilters/TaskFilters.tsx
=> feat: add placeHolder to picker with no title

packages/apps/sale/src/components/atoms/DropdownGeneralView/DropdownGeneralView.tsx, packages/apps/sale/src/components/molecules/SaleOrderDropdownCards/SaleOrderDropdownCards.tsx, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/models/objectFields.ts
=> feat: add pricelist inf in SaleOrder details

packages/apps/project/src/index.ts
=> feat: modify menu icon

packages/apps/project/src/components/atoms/DatesDisplay/DatesDisplay.tsx, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json
RM#84018
sorry misktake about branch name
=> feat: improve project dates display

changelogs/unreleased/83735.json, packages/ui/__tests__/components/organisms/SingleSelectScrollList.test.js, packages/ui/src/components/organisms/SingleSelectScrollList/SingleSelectScrollList.tsx, packages/ui/src/components/organisms/index.tsx, packages/ui/stories/organisms/SingleSelectScrollList.stories.tsx
=> feat: add new SingleSelectScrollList component

packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
=> feat: change trad validate cart

packages/apps/sale/src/api/cart-api.js, packages/apps/sale/src/api/index.ts, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/cartSlice.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
=> feat: add API action on empty cart

packages/apps/sale/src/api/index.ts, packages/apps/sale/src/api/product-api.js, packages/apps/sale/src/components/organisms/ProductCategorySearchBar/ProductCategorySearchBar.tsx, packages/apps/sale/src/components/organisms/index.ts, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/productSlice.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/models/objectFields.ts, packages/apps/sale/src/models/searchFields.ts, packages/apps/sale/src/screens/product/ProductSaleListScreen.tsx
=> feat: add filters on products and services list view

packages/apps/project/src/screens/ProjectDetailsScreen.tsx
=> fix: hide tree view based on project config

packages/apps/sale/src/components/atoms/DropdownGeneralView/AdressLine.tsx
=> fix: display issue on Sale order Adress

changelogs/unrealesed/84375.json, packages/core/src/components/external/Stopwatch/Stopwatch.tsx
=> fix: Stopwatch use flewWrap to manage width issue

changelogs/unreleased/84286.json, packages/ui/src/components/molecules/MultiValuePickerButton/MultiValuePickerButton.tsx, packages/ui/src/components/molecules/RightIconButton/RightIconButton.tsx, packages/ui/src/components/organisms/Picker/Picker.tsx
=> fix: put place holder for MultieValuePickerButton to one line

changelogs/unreleased/84203.json, packages/core/src/components/external/Camera/Camera.tsx
=> fix: camera issue on iOS

changelogs/unreleased/83968.json, packages/apps/sale/src/components/molecules/SaleOrderHeader/SaleOrderHeader.tsx
=> refactor: improve badges display on SaleOrderDetails

changelogs/unreleased/83737.json, packages/core/src/components/templates/SingleSelectSearchListView/SingleSelectSearchListView.tsx, packages/core/src/components/templates/index.js
=> feat: add component SingleSelectSearchListView

changelogs/unreleased/83854.json, packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx, packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
=> feat: add possibility to display icon on Dropdown

packages/apps/project/src/api/index.ts, packages/apps/project/src/api/project-task-api.js, packages/apps/project/src/components/pages/TaskView/TaskView.tsx, packages/apps/project/src/components/templates/TaskFilters/TaskFilters.tsx, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/projectTaskSlice.js, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json, packages/apps/project/src/screens/TaskListScreen.tsx
=> feat: add filter taskCategory in task filters

packages/apps/sale/src/api/cart-api.js, packages/apps/sale/src/components/molecules/CartHeader/CartHeader.tsx, packages/apps/sale/src/components/organisms/CustomerSearchBar/CustomerSearchBar.tsx, packages/apps/sale/src/components/templates/CompanyPicker/CompanyPicker.tsx
=> feat: enable compsany update on Cart

changelogs/unreleased/84677.json, packages/core/src/auth/components/molecules/UserCard/UserCard.tsx
=> fix: logout button out of card on user screen

changelogs/unreleased/83875.json, packages/apps/stock/src/api/index.ts, packages/apps/stock/src/api/supplier-arrival-line-api.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineActionCard/SupplierArrivalLineActionCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js, packages/apps/stock/src/components/templates/supplierArrival/index.js, packages/apps/stock/src/features/asyncFunctions-index.ts, packages/apps/stock/src/features/supplierArrivalLineSlice.js, packages/apps/stock/src/i18n/en.json, packages/apps/stock/src/i18n/fr.json, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
=> feat: enable line splitting on supplier arrival

packages/apps/sale/src/components/molecules/CartLineActionCard/CartLineActionCard.tsx
=> refactor: keep actions view open whenusing an action on CartLineActionCard

packages/apps/project/src/api/index.ts, packages/apps/project/src/api/project-task-api.js, packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx, packages/apps/project/src/components/pages/TaskLinkView/TaskLinkView.tsx, packages/apps/project/src/components/pages/index.ts, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/projectTaskSlice.js, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json, packages/apps/project/src/models/objectFields.ts, packages/apps/project/src/screens/TaskDetailsScreen.tsx, packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx
=> feat: add TaskLinkView

packages/apps/sale/src/components/molecules/CartHeader/CartHeader.tsx
=> fix: zIndex issue on CartHeader

changelogs/unreleased/80182.json, packages/apps/stock/src/api/index.ts, packages/apps/stock/src/api/stock-move-line-api.js, packages/apps/stock/src/components/organisms/StockMoveHeader/StockMoveHeader.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveSearchLineContainer/InternalMoveSearchLineContainer.js, packages/apps/stock/src/hooks/stock-move-lines.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectProductScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectTrackingScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveSelectProductScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveSelectTrackingScreen.js
=> feat: add missing quantity tag on stock move line

packages/apps/sale/src/api/product-api.js, packages/apps/sale/src/screens/cart/CatalogScreen.tsx, packages/apps/sale/src/screens/product/ProductSaleListScreen.tsx
=> feat:  take web sale configs into account

packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json, packages/apps/project/src/index.ts, packages/apps/project/src/models/objectFields.ts, packages/apps/project/src/screens/ActiveProjectScreen.tsx, packages/apps/project/src/screens/ProjectDetailsScreen.tsx, packages/apps/project/src/screens/index.ts
=> feat: add active project management

packages/ui/src/components/organisms/DraggableWrapper/DraggableWrapper.tsx
=> refactor: restrict DraggableWrapper to avoid sending it out of screen

packages/apps/sale/src/api/index.ts, packages/apps/sale/src/api/sale-order-api.js, packages/apps/sale/src/components/atoms/SaleOrderBottomButton/SaleOrderBottomButton.tsx, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/saleOrderSlice.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/index.ts, packages/apps/sale/src/utils/index.ts, packages/apps/sale/src/utils/sale-order.helpers.ts
=> feat: add possibility to changeSaleOrder

packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/index.ts
=> feat: add  cart tool

packages/apps/sale/src/components/molecules/DropdownMultipleQuantities/DropdownMultipleQuantities.tsx, packages/apps/sale/src/components/organisms/ProductDropdownCard/ProductDropdownCard.tsx, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json
=> feat: improve multiple quantities display

changelogs/unreleased/85434.json, packages/apps/hr/src/models/forms.ts
=> fix: change product input to not required on TimesheetLine form

changelogs/unreleased/85476.json, packages/apps/stock/src/components/templates/product/ProductCardStockIndicatorList/ProductCardStockIndicatorList.js
=> fix: error when clicking of product indicator

changelogs/unreleased/84414.json, packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx, packages/ui/src/components/atoms/Screen/Screen.tsx
=> fix: prevent fixedItems from being cut on Screen

changelogs/unreleased/85478.json, packages/ui/src/components/organisms/FloatingButton/FloatingButton.tsx
=> fix: make form tools always visible in edition mode

changelogs/unreleased/85480.json, packages/apps/hr/src/screens/timesheet/TimerFormScreen.js, packages/apps/intervention/src/screens/intervention/InterventionQuestionFormScreen.tsx
=> refactor: add edition mode by default on form views when user navigates to create or modify an object

packages/apps/stock/src/api/index.ts, packages/apps/stock/src/api/stock-correction-api.js, packages/apps/stock/src/api/tracking-number-api.js, packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionTrackingNumberSelect/StockCorrectionTrackingNumberSelect.tsx, packages/apps/stock/src/components/templates/stockCorrection/index.js, packages/apps/stock/src/features/asyncFunctions-index.ts, packages/apps/stock/src/features/stockCorrectionSlice.js, packages/apps/stock/src/i18n/en.json, packages/apps/stock/src/i18n/fr.json, packages/apps/stock/src/screens/stockCorrections/StockCorrectionCreationScreen.js, packages/apps/stock/src/screens/stockCorrections/StockCorrectionDetailsScreen.js
=> fix: add trackingnumber managment on stock correction

changelogs/unreleased/85325.json, packages/core/src/auth/i18n/en.json, packages/core/src/auth/i18n/fr.json, packages/core/src/auth/screens/SettingsScreen.js, packages/core/src/components/templates/GlobalToolBox/GlobalToolBox.tsx, packages/ui/src/config/ConfigContext.tsx
=> feat: add configuration to activate/desactivate toolbox

packages/apps/sale/src/api/cart-line-api.js, packages/apps/sale/src/api/index.ts, packages/apps/sale/src/components/molecules/CartLineValidationButton/CartLineValidationButton.tsx, packages/apps/sale/src/components/organisms/ProductSearchBar/ProductSearchBar.tsx, packages/apps/sale/src/components/organisms/index.ts, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/cartLineSlice.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/models/objectFields.ts, packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx, packages/apps/sale/src/screens/cart/CartLineDetailsScreen.tsx
=> feat: enable cart line creation

changelogs/unreleased/85158.json, changelogs/unreleased/85158_formSlider.json, changelogs/unreleased/85158_slider.json, jest/setup-mocks.js, package.json, packages/ui/__tests__/components/atoms/Slider.test.js, packages/ui/__tests__/components/molecules/FormSlider.test.js, packages/ui/package.json, packages/ui/src/components/atoms/Slider/Slider.tsx, packages/ui/src/components/atoms/index.tsx, packages/ui/src/components/molecules/FormSlider/FormSlider.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/stories/atoms/Slider.stories.tsx, packages/ui/stories/molecules/FormSlider.stories.tsx, yarn.lock
=> feat: add Slider component

packages/apps/hr/src/api/project-api.js, packages/apps/hr/src/components/templates/ProjectSearchBar/ProjectSearchBar.tsx, packages/apps/hr/src/models/forms.ts
=> fix: remove useless criteria and add filter on business projects

packages/apps/project/src/components/pages/TaskView/TaskView.tsx, packages/apps/project/src/components/templates/TaskFilters/TaskFilters.tsx, packages/apps/project/src/components/templates/TaskStatusSearchBar/TaskStatusSearchBar.tsx, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/projectTaskSlice.js, packages/apps/project/src/models/forms.ts, packages/apps/project/src/models/objectFields.ts, packages/apps/project/src/models/typeObjects.ts, packages/apps/project/src/screens/TaskFormScreen.tsx, packages/apps/project/src/screens/TaskListScreen.tsx
=> feat: improve status management

changelogs/unreleased/85783.json, packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
=> fix: keyboard issue on iOS when using html input

packages/apps/sale/src/api/index.ts, packages/apps/sale/src/api/sale-order-api.js, packages/apps/sale/src/components/organisms/CustomerSearchBar/CustomerSearchBar.tsx, packages/apps/sale/src/components/organisms/ProductSearchBar/ProductSearchBar.tsx, packages/apps/sale/src/components/organisms/SaleQuotationCreationButtons/SaleQuotationCreationButtons.tsx, packages/apps/sale/src/components/organisms/SaleQuotationCreationQuantityCard/SaleQuotationCreationQuantityCard.tsx, packages/apps/sale/src/components/organisms/index.ts, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/saleOrderSlice.js, packages/apps/sale/src/hooks/use-sale-header-actions.ts, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/screens/saleOrder/SaleQuotationCreationScreen.tsx, packages/apps/sale/src/screens/saleOrder/index.ts
=> feat: enable quotation creation

packages/apps/sale/src/api/cart-api.js, packages/apps/sale/src/api/index.ts, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/cartSlice.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/index.ts, packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx, packages/apps/sale/src/screens/product/ProductSaleDetailsScreen.tsx
=> feat: register add product cart tool in module

packages/apps/hr/src/features/timesheetLineSlice.js, packages/apps/project/src/components/organisms/LogTimeButton/LogTimeButton.tsx, packages/apps/project/src/components/pages/TimeView/TimeView.tsx, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/timesheetLinesSlice.js, packages/apps/project/src/models/forms.ts, packages/apps/project/src/models/objectFields.ts, packages/apps/project/src/screens/ProjectDetailsScreen.tsx, packages/apps/project/src/screens/TaskDetailsScreen.tsx
=> feat: manage time log on project and task

changelogs/unreleased/85927.json, packages/core/src/index.ts
=> fix: add export scan hook

packages/apps/hr/src/api/project-api.js
=> fix: modify project filter

packages/core/src/components/templates/GlobalToolBox/GlobalToolBox.tsx
=> refactor: change default toolbox position

changelogs/unreleased/83948.json, packages/ui/src/components/organisms/FloatingButton/FloatingActionButton.tsx, packages/ui/src/components/organisms/FloatingButton/Indicator.tsx
=> fix: display issue when opening FloatingButton

changelogs/unreleased/85850.json, changelogs/unreleased/85850_type.json, packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx, packages/ui/src/components/templates/BottomBar/BottomBar.tsx, packages/ui/src/components/templates/BottomBar/types.helper.ts
=> feat: add possibility to define active item from outside on BottomBar

packages/apps/sale/src/index.ts, packages/apps/sale/src/screens/product/ProductSaleDetailsScreen.tsx, packages/apps/sale/src/screens/saleOrder/SaleOrderLineDetailsScreen.tsx, packages/apps/stock/src/screens/products/ProductDetailsScreen.js, packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js, packages/core/src/navigator/ActiveScreenProvider.ts, packages/core/src/navigator/index.ts
=> feat: improve context management on screen

ios/Podfile.lock
Update Podfile.lock before new version
=> chore: add Podfile.lock

changelogs/unreleased/85153.json, packages/core/src/auth/components/molecules/TranslationsButton/TranslationsButton.tsx, packages/core/src/auth/models/objectFields.ts, packages/core/src/i18n/component/Translator.js, packages/core/src/i18n/helpers/langages.ts, packages/core/src/i18n/hooks/use-translator.ts, packages/core/src/i18n/i18n.ts
=> feat: add region support on translations

packages/apps/project/src/components/molecules/TaskActionCard/TaskActionCard.tsx, packages/apps/project/src/screens/TaskDetailsScreen.tsx
=> feat: manage shortcut to log time on task

changelogs/unreleased/86024.json, packages/core/src/app/RootNavigator.js, packages/core/src/auth/screens/SettingsScreen.js, packages/core/src/hooks/use-storage-config.ts, packages/core/src/index.ts, packages/ui/src/config/ConfigContext.tsx
=> feat: add ui config into storage with hooks

packages/apps/manufacturing/src/api/prod-product-api.js, packages/apps/manufacturing/src/api/product-indicators-api.js, packages/apps/project/src/api/project-api.js, packages/apps/project/src/api/project-task-api.js, packages/apps/project/src/api/reporting-api.js, packages/apps/project/src/api/timesheet-lines-api.js, packages/apps/sale/src/api/cart-api.js, packages/apps/sale/src/api/cart-line-api.js, packages/apps/sale/src/api/complementary-product-api.js, packages/apps/sale/src/api/customer-api.js, packages/apps/sale/src/api/customer-delivery-api.js, packages/apps/sale/src/api/price-list-line-api.js, packages/apps/sale/src/api/product-api.js, packages/apps/sale/src/api/sale-config-api.js, packages/apps/sale/src/api/sale-order-api.js, packages/apps/sale/src/api/sale-order-line-api.js, packages/apps/stock/src/api/product-indicators-api.js, packages/apps/stock/src/api/tracking-number-api.js
=> feat: use model and action api providers

changelogs/unreleased/86102/json, packages/core/src/index.ts
=> fix: export useCameraScanner hook

changelogs/unreleased/86107.json, packages/core/src/components/external/Camera/Camera.tsx
=> fix: add new type for scan

changelogs/unreleased/86177.json, packages/ui/src/components/templates/BottomBar/BarItem.tsx, packages/ui/src/components/templates/BottomBar/BottomBar.tsx, packages/ui/src/components/templates/BottomBar/ItemTitle.tsx
=> feat: add possibility to manage active title globally on BottomBar

changelogs/unreleased/86381.json, packages/apps/stock/src/components/templates/product/ProductCardStockIndicatorList/ProductCardStockIndicatorList.js
=> fix: disable pressable area on IndicatorChart in stock

changelogs/unreleased/86450.json, changelogs/unreleased/86450_chips.json, packages/core/src/components/templates/MailMessageView/MailMessageView.js, packages/ui/src/components/molecules/Chip/Chip.tsx, packages/ui/src/components/organisms/ChipSelect/ChipSelect.tsx
=> fix: display mail messages chips on one line

changelogs/unreleased/86455.json, packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx, packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx
=> fix: trigger period computation on Timesheet update

changelogs/unreleased/86477.json, packages/core/src/index.ts
=> fix: Session export

changelogs/unreleased/86448.json, packages/apps/stock/src/screens/internalMoves/InternalMoveCreationScreen.js, packages/apps/stock/src/screens/stockCorrections/StockCorrectionCreationScreen.js, packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx
=> fix: improve style on creation screen

changelogs/unreleased/86499.json, packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js, packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx
=> fix: cannot delete expense and expense line

changelogs/unreleased/86253.json, docs/doc/en/Outil/Gestion_des_headers.md, docs/doc/fr/Outil/Gestion_des_headers.md, packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js, packages/core/src/header/HeaderActionsProvider.ts, packages/core/src/header/types.ts, packages/core/src/navigator/drawer/Header.js
=> feat: add possibility to define generic header actions

changelogs/unreleased/86451.json, packages/ui/src/components/atoms/Screen/Screen.tsx
=> fix: hide navigation bar when keyboard disappear

changelogs/unreleased/85710.json, packages/core/src/components/pages/FormView/Custom/CustomTagList.tsx, packages/core/src/components/pages/FormView/Custom/index.ts, packages/core/src/forms/studio/api.helpers.ts, packages/core/src/forms/studio/display.helpers.ts
=> feat: add management of M2M and M2O fields on custom fields form

changelogs/unreleased/86812.json, packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
=> fix: remove add button on expense line form

changelogs/unreleased/86811.json, packages/ui/src/components/organisms/ActionCard/ActionCard.tsx
=> fix: actions display issue on ActionCard

changelogs/unreleased/87053.json, packages/apps/hr/src/features/asyncFunctions-index.ts
=> fix: add missing exports for reducers on hr

android/app/src/main/AndroidManifest.xml, changelogs/unreleased/86837.json, ios/AosMobile/Info.plist, packages/core/src/components/external/WebView/WebView.tsx
=> feat: authorize geolocation for webView

changelogs/unreleased/87258.json, packages/core/src/api/meta-module-api.ts, packages/core/src/models/objectFields.ts
=> fix: replace get by createStandardSearch

changelogs/unreleased/87049.json, packages/core/src/sessions/components/inputs/SessionInputs.js
=> fix: improve session refresh on input with unique mode

changelogs/unreleased/87305.json, packages/apps/stock/src/api/tracking-number-api.js
=> fix: API path used for adding tracking number

changelogs/unreleased/86572.json, packages/ui/src/components/molecules/Increment/Increment.tsx, packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx
=> feat: add autoselect on focus

changelogs/unreleased/87288.json, packages/ui/src/components/templates/TreeView/BranchCard.tsx
=> fix: display issue on BranchCard

changelogs/unreleased/87597.json, packages/core/src/header/hooks.js
=> fix: reduce number of calls for print action

changelogs/unreleased/86490_Breadcrumb.json, changelogs/unreleased/86490_SearchTreeView.json, packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx, packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx, packages/ui/__tests__/components/molecules/Breadcrumb.test.js, packages/ui/src/components/molecules/Breadcrumb/Breadcrumb.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/stories/molecules/Breadcrumb.stories.tsx
=> feat: add Breadcrumb on SearchTreeView

changelogs/unreleased/86491.json, packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
=> feat: add possibility to define default value for parent filter on TreeView

packages/apps/dms/src/api/document-api.js, packages/apps/dms/src/api/index.ts, packages/apps/dms/src/components/atoms/AuthorFilter/AuthorFilter.tsx, packages/apps/dms/src/components/atoms/DirectoryCard/DirectoryCard.tsx, packages/apps/dms/src/components/atoms/DocumentCard/DocumentCard.tsx, packages/apps/dms/src/components/atoms/index.ts, packages/apps/dms/src/components/index.ts, packages/apps/dms/src/components/molecules/DocumentActionCard/DocumentActionCard.tsx, packages/apps/dms/src/components/molecules/index.ts, packages/apps/dms/src/components/organisms/DocumentsFilters/DocumentsFilters.tsx, packages/apps/dms/src/components/organisms/index.ts, packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx, packages/apps/dms/src/components/templates/index.ts, packages/apps/dms/src/features/asyncFunctions-index.ts, packages/apps/dms/src/features/documentSlice.js, packages/apps/dms/src/features/index.js, packages/apps/dms/src/i18n/en.json, packages/apps/dms/src/i18n/fr.json, packages/apps/dms/src/index.ts, packages/apps/dms/src/models/index.ts, packages/apps/dms/src/models/objectFields.ts, packages/apps/dms/src/models/searchFields.ts, packages/apps/dms/src/models/sortFields.ts, packages/apps/dms/src/screens/AllDocumentsScreen.tsx, packages/apps/dms/src/screens/index.ts, packages/apps/dms/src/types/file.ts, packages/apps/dms/src/types/index.ts, packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx, packages/core/src/components/templates/UserSearchBar/UserSearchBar.js, packages/ui/src/components/templates/TreeView/BranchCard.tsx
=> feat: create all documents view

changelogs/unreleased/87274.json, changelogs/unreleased/87274_CardIndicator.json, changelogs/unreleased/87274_InfoBubble.json, packages/core/src/navigator/drawer/DrawerContent.js, packages/core/src/navigator/drawer/MenuIconButton.js, packages/ui/__tests__/components/molecules/CardIndicator.test.js, packages/ui/__tests__/components/organisms/InfoBubble.test.js, packages/ui/src/components/molecules/CardIndicator/CardIndicator.tsx, packages/ui/src/components/organisms/InfoBubble/InfoBubble.tsx, packages/ui/stories/molecules/CardIndicator.stories.tsx, packages/ui/stories/organisms/InfoBubble.stories.tsx
=> fix: improve display of warning error

changelogs/unreleased/87393.json, packages/ui/src/components/molecules/Increment/Increment.tsx
=> refactor: manage format on blur/focus on the Increment input

packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx, packages/apps/dms/src/i18n/en.json, packages/apps/dms/src/i18n/fr.json, packages/apps/dms/src/index.ts, packages/apps/dms/src/screens/AllDocumentsScreen.tsx, packages/apps/dms/src/screens/MyFavoriteDocumentsScreen.tsx, packages/apps/dms/src/screens/index.ts, packages/apps/dms/src/utils/index.ts, packages/apps/dms/src/utils/moduleHelper.ts, packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
=> feat: create menu entries with user favorite folders

changelogs/unreleased/87714.json, packages/ui/src/components/molecules/Increment/Increment.tsx
=> fix: issue on save for the Increment value on form

changelogs/unreleased/87876.json, packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js, packages/core/src/header/types.ts
=> feat: add possibility to use async functions on generic action

changelogs/unreleased/87640.json, packages/apps/intervention/src/api/equipment-api.js, packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx
=> fix: filter issue with chips on CustomerParkScreen

packages/apps/dms/src/api/document-api.js, packages/apps/dms/src/features/documentSlice.js, packages/apps/dms/src/i18n/en.json, packages/apps/dms/src/i18n/fr.json, packages/apps/dms/src/screens/MyFavoriteDocumentsScreen.tsx
=> feat: create favorites files screen

packages/apps/dms/src/api/document-api.js, packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
=> fix: filter issue with chips on DocumentList

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/api/leave-api.js, packages/apps/hr/src/components/molecules/LeaveActionCard/LeaveActionCard.tsx, packages/apps/hr/src/components/molecules/LeaveDetailsButtons/LeaveDetailsButtons.tsx, packages/apps/hr/src/components/templates/LeaveRefusalPopup/LeaveRefusalPopup.tsx, packages/apps/hr/src/components/templates/index.js, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/leaveSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx, packages/apps/hr/src/screens/leaveRequests/LeaveListScreen.tsx
=> feat: add action on leave request

packages/core/src/apiProviders/Standard/requests.helper.ts
=> fix: remove default domain

packages/apps/dms/src/api/document-api.js, packages/apps/dms/src/api/index.ts, packages/apps/dms/src/hooks/use-dms-header-actions.ts, packages/apps/dms/src/i18n/en.json, packages/apps/dms/src/i18n/fr.json, packages/apps/dms/src/models/forms.ts, packages/apps/dms/src/screens/AttachedFilesScreen.tsx, packages/apps/dms/src/screens/DocumentFormScreen.tsx, packages/apps/dms/src/screens/index.ts, packages/apps/dms/src/utils/attachedFilesGenericAction.ts, packages/apps/dms/src/utils/index.ts
=> feat: manage attached files header action

changelogs/unreleased/88563.json, packages/apps/crm/src/hooks/use-crm-header-actions.ts, packages/apps/helpdesk/src/hooks/use-helpdesk-header-actions.ts, packages/apps/intervention/src/hooks/use-intervention-header-actions.ts, packages/apps/project/src/hooks/use-project-header-actions.ts, packages/apps/sale/src/hooks/use-sale-header-actions.ts, packages/apps/stock/src/hooks/use-stock-header-actions.js
=> refactor: transform attachedFileScreenTitle into options in headerActionsProvider

changelogs/unreleased/88623.json, packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js, packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js
=> fix: issue on inventory line creation

changelogs/unreleased/88098.json, packages/core/src/auth/api/company-api.js, packages/core/src/auth/components/molecules/UserCard/UserCard.tsx, packages/core/src/auth/features/asyncFunctionsIndex.js, packages/core/src/auth/features/userSlice.js
=> feat: manage company update on AOS

packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
=> refactor: use props isHideableParentSearch on DocumentList

changelogs/unreleased/89190.json, packages/apps/stock/src/features/asyncFunctions-index.ts
=> fix: add missing export of updateStockMoveLineTrackingNumber from trackingNumberSlice

changelogs/unreleased/86533.json, packages/core/src/apiProviders/Action/AosActionApi.ts, packages/core/src/apiProviders/Action/utils.ts
=> feat: add option to ignore action api

changelogs/unreleased/69728.json, packages/core/src/navigator/Navigator.js
=> refactor: stack not reset on navigation

changelogs/unreleased/88457.json, packages/apps/helpdesk/src/api/customer-api.js, packages/apps/helpdesk/src/api/project-api.js, packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js, packages/apps/helpdesk/src/components/templates/CustomerSearchBar/CustomerSearchBar.js, packages/apps/helpdesk/src/components/templates/ProjectSearchBar/ProjectSearchBar.js
=> refactor: manage company in data fetching in helpdesk

changelogs/unreleased/88462.json, changelogs/unreleased/cart.json, packages/apps/sale/src/api/cart-api.js, packages/apps/sale/src/api/customer-api.js, packages/apps/sale/src/api/customer-delivery-api.js, packages/apps/sale/src/api/product-api.js, packages/apps/sale/src/api/sale-config-api.js, packages/apps/sale/src/api/sale-order-api.js, packages/apps/sale/src/components/atoms/SaleOrderBottomButton/SaleOrderBottomButton.tsx, packages/apps/sale/src/components/organisms/CustomerSearchBar/CustomerSearchBar.tsx, packages/apps/sale/src/components/organisms/DropDownSaleOrderView/DropDownSaleOrderView.tsx, packages/apps/sale/src/components/pages/SaleOrderListView/SaleOrderListView.tsx, packages/apps/sale/src/index.ts, packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx, packages/apps/sale/src/screens/cart/CatalogScreen.tsx, packages/apps/sale/src/screens/client/ClientSaleListScreen.tsx
=> refactor: manage company in data fetching in sale

changelogs/unreleased/86537.json, changelogs/unreleased/89626_date.json, changelogs/unreleased/89626_messagebox.json, packages/core/src/api/mail-message-api.ts, packages/core/src/components/templates/MailMessageView/MailMessageView.js
=> feat: add props to hide message box and filter messages by date on MailMessageView

changelogs/unreleased/88460.json, packages/apps/project/src/api/project-api.js, packages/apps/project/src/api/project-task-api.js, packages/apps/project/src/components/pages/SubProjectView/SubProjectView.tsx, packages/apps/project/src/components/pages/TaskView/TaskView.tsx, packages/apps/project/src/components/templates/ProjectListView/ProjectListView.tsx, packages/apps/project/src/components/templates/ProjectSearchBar/ProjectSearchBar.tsx, packages/apps/project/src/screens/TaskListScreen.tsx
=> refactor: manage company in data fetching in project

packages/apps/purchase/src/api/index.ts, packages/apps/purchase/src/api/purchase-request-api.js, packages/apps/purchase/src/components/organisms/RequestButtons/RequestButtons.tsx, packages/apps/purchase/src/features/asyncFunctions-index.ts, packages/apps/purchase/src/features/purchaseRequestSlice.js, packages/apps/purchase/src/i18n/en.json, packages/apps/purchase/src/i18n/fr.json
=> feat: add API actions on status buttons

changelogs/unreleased/89400.json, packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js, packages/apps/crm/src/components/organisms/DropdownContactView/DropdownContactView.tsx, packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js, packages/apps/crm/src/i18n/en.json, packages/apps/crm/src/i18n/fr.json
=> feat: renane Address to Main Adress Clients and Prospects

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/api/leave-api.js, packages/apps/hr/src/components/atoms/LeaveStartEndOn/LeaveStartEndOn.tsx, packages/apps/hr/src/components/templates/CompleteRequestButtons/CompleteRequestButtons.tsx, packages/apps/hr/src/features/asyncFunctions-index.ts, packages/apps/hr/src/features/leaveSlice.js, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx
=> feat: add API on leave request creation assistant

packages/apps/hr/src/components/atoms/LeaveAvailableDuractionCard/LeaveAvailableDuractionCard.tsx, packages/apps/hr/src/components/templates/CompleteRequestQuantityCard/CompleteRequestQuantityCard.tsx, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx, packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx
=> refactor: show leave reason available quantity only on managed reason

changelogs/unreleased/88455.json, packages/apps/hr/src/api/expense-api.js, packages/apps/hr/src/api/manuf-order-api.js, packages/apps/hr/src/api/project-api.js, packages/apps/hr/src/api/timesheet-api.js, packages/apps/hr/src/components/templates/DraftExpensePicker/DraftExpensePicker.js, packages/apps/hr/src/components/templates/DraftTimesheetPicker/DraftTimesheetPicker.tsx, packages/apps/hr/src/components/templates/ExpenseWaitingValidationSearchBar/ExpenseWaitingValidationSearchBar.js, packages/apps/hr/src/components/templates/OperationOrderSearchBar/OperationOrderSearchBar.tsx, packages/apps/hr/src/components/templates/ProjectTaskSearchBar/ProjectTaskSearchBar.tsx, packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx, packages/apps/hr/src/components/templates/TimesheetFilters/TimesheetFilters.js, packages/apps/hr/src/components/templates/TimesheetWaitingValidationSearchBar/TimesheetWaitingValidationSearchBar.js, packages/apps/hr/src/screens/expense/ExpenseListScreen.js, packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js
=> refactor: manage company data in hr

changelogs/unreleased/89993.json, packages/apps/stock/src/index.ts, packages/apps/stock/src/screens/auth/index.js
=> fix: wrong export of UserScreen

changelogs/unreleased/90186.json, packages/apps/stock/src/api/customer-delivery-line-api.js, packages/apps/stock/src/api/internal-move-line-api.js, packages/apps/stock/src/api/inventory-line-api.js, packages/apps/stock/src/api/partner-api.js, packages/apps/stock/src/api/product-api.js, packages/apps/stock/src/api/product-indicators-api.js, packages/apps/stock/src/api/stock-correction-reason-api.js, packages/apps/stock/src/api/stock-location-api.js, packages/apps/stock/src/api/stock-location-line-api.js, packages/apps/stock/src/api/supplier-arrival-line-api.js, packages/apps/stock/src/api/supplier-catalog-api.js, packages/apps/stock/src/api/unit-api.js
=> fix: add missing sortKey on search functions in stock

changelogs/unreleased/87444.json, changelogs/unreleased/87444_stock.json, packages/apps/stock/src/api/stock-location-api.js, packages/core/src/apiProviders/Model/utils.ts, packages/core/src/apiProviders/Standard/index.ts, packages/core/src/apiProviders/Standard/requests.helper.ts
=> feat: add tool to manage search on hierarchical objects

packages/apps/hr/src/api/leave-api.js, packages/apps/hr/src/components/templates/CompleteRequestButtons/CompleteRequestButtons.tsx, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx
=> feat: use AOS API to check consistency on leave request

packages/apps/purchase/src/api/index.ts, packages/apps/purchase/src/api/purchase-request-line-api.js, packages/apps/purchase/src/components/atoms/RequestLineCard/RequestLineCard.tsx, packages/apps/purchase/src/components/templates/HorizontalOrRuleText/HorizontalOrRuleText.tsx, packages/apps/purchase/src/components/templates/ProductSearchBar/ProductSearchBar.tsx, packages/apps/purchase/src/features/asyncFunctions-index.ts, packages/apps/purchase/src/features/purchaseRequestLineSlice.js, packages/apps/purchase/src/i18n/en.json, packages/apps/purchase/src/i18n/fr.json, packages/apps/purchase/src/index.ts, packages/apps/purchase/src/models/forms.ts, packages/apps/purchase/src/models/index.ts, packages/apps/purchase/src/models/objectFields.ts, packages/apps/purchase/src/screens/RequestCreationScreen.tsx, packages/apps/purchase/src/screens/RequestLineFormScreen.tsx, packages/apps/purchase/src/screens/RequestLineListScreen.tsx, packages/apps/purchase/src/screens/index.ts, packages/ui/src/components/molecules/HorizontalRuleText/HorizontalRuleText.tsx
=> feat: add purchase request line form view

changelogs/unreleased/90595.json, changelogs/unreleased/90595_PeriodInput_DateConfig.json, changelogs/unreleased/90595_PeriodInput_Error.json, packages/apps/crm/src/components/organisms/EventPeriodInput/EventPeriodInput.tsx, packages/apps/crm/src/components/organisms/index.js, packages/apps/crm/src/models/forms.ts, packages/apps/crm/src/screens/event/EventFormScreen.js, packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
=> feat: add PeriodInput on event form on crm

changelogs/unreleased/90855_formincrement.json, changelogs/unreleased/90855_spacer.json, packages/apps/hr/src/components/templates/DistanceIncrement/DistanceIncrement.js, packages/ui/src/components/molecules/FormIncrementInput/FormIncrementInput.tsx
=> fix: add spacer translations and callback for useless refresh

changelogs/unreleased/89763.json, packages/core/src/components/templates/PopupMinimalRequiredVersion/PopupMinimalRequiredVersion.js, packages/core/src/components/templates/PopupMinimalRequiredVersion/PopupMinimalRequiredVersion.tsx, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/tools/FileDownloader.ts
=> feat: add APK download management for version update

changelogs/unreleased/90807.json, changelogs/unreleased/90807_core.json, packages/apps/sale/src/api/cart-api.js, packages/apps/sale/src/api/cart-line-api.js, packages/apps/sale/src/components/molecules/CatalogActionCard/CatalogActionCard.tsx, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/core/src/apiProviders/utils.ts
=> fix : improve the error message when adding an item to the cart and there is no cart

packages/apps/hr/src/api/index.ts, packages/apps/hr/src/api/leave-api.js, packages/apps/hr/src/components/atoms/LeaveAvailableDuractionCard/LeaveAvailableDuractionCard.tsx, packages/apps/hr/src/components/templates/CompleteRequestQuantityCard/CompleteRequestQuantityCard.tsx, packages/apps/hr/src/i18n/en.json, packages/apps/hr/src/i18n/fr.json, packages/apps/hr/src/models/objectFields.ts, packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx, packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx
=> feat: add API on availability check

docs/doc/en/GettingStarted.md, docs/doc/fr/GettingStarted.md
=> doc: add enterprise module management

packages/apps/purchase/src/api/index.ts, packages/apps/purchase/src/api/purchase-request-api.js, packages/apps/purchase/src/components/templates/RequestCreationButtons/RequestCreationButtons.tsx, packages/apps/purchase/src/features/asyncFunctions-index.ts, packages/apps/purchase/src/features/purchaseRequestSlice.js, packages/apps/purchase/src/i18n/en.json, packages/apps/purchase/src/i18n/fr.json, packages/apps/purchase/src/screens/RequestCreationScreen.tsx, packages/apps/purchase/src/types/request-creation.ts
=> feat: add API action on request creation

changelogs/unreleased/91463.json, packages/apps/intervention/src/api/intervention-api.js
=> fix: modify intervention user filter

changelogs/unreleased/89849.json, changelogs/unreleased/89849_Stock.json, packages/apps/stock/src/api/alternative-barcode-api.js, packages/apps/stock/src/api/index.ts, packages/apps/stock/src/api/product-api.js, packages/apps/stock/src/api/stock-location-line-api.js, packages/apps/stock/src/components/templates/AvailableProductsSearchBar/AvailableProductsSearchBar.js, packages/apps/stock/src/components/templates/ProductSearchBar/ProductSearchBar.js, packages/apps/stock/src/components/templates/ProductTrackingNumberSearchBar/ProductTrackingNumberSearchBar.js, packages/apps/stock/src/features/alternativeBarcodeSlice.js, packages/apps/stock/src/features/asyncFunctions-index.ts, packages/apps/stock/src/features/index.js, packages/apps/stock/src/features/productSlice.js, packages/apps/stock/src/i18n/en.json, packages/apps/stock/src/i18n/fr.json, packages/apps/stock/src/models/objectFields.ts, packages/apps/stock/src/models/searchFields.ts, packages/apps/stock/src/screens/products/ProductListScreen.js, packages/core/src/components/templates/DoubleScannerSearchBar/DoubleScannerSearchBar.tsx, packages/core/src/components/templates/SearchListAlternativeBarCode/SearchListAlternativeBarCode.tsx, packages/core/src/components/templates/index.js, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json
=> feat: add SearchListAlternativeBarCode component

changelogs/unreleased/90996.json, packages/apps/quality/src/screens/ControlEntryFormScreen.js
=> fix: issue on control entry completion

changelogs/unreleased/90998.json, packages/apps/quality/src/components/atoms/ControlEntrySampleLineHeader/ControlEntrySampleLineHeader.tsx
=> fix: display issue on control entry line with long title

changelogs/unreleased/91544.json, packages/apps/stock/src/screens/products/ProductListScreen.js, packages/core/src/components/templates/DoubleScannerSearchBar/DoubleScannerSearchBar.tsx, packages/core/src/components/templates/SearchListView/SearchListView.tsx
=> feat: add possibility to define a custom search bar on SearchListView

changelogs/unreleased/91566.json, packages/ui/src/components/organisms/ProgressBar/ProgressBar.tsx
=> fix: progress bar always display a progress even when value is 0

changelogs/unreleased/91546.json, packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
=> fix: crash when no management of parent from outside of tree view

packages/apps/crm/src/api/contact-info-api.js, packages/apps/crm/src/api/index.ts, packages/apps/crm/src/components/molecules/ContactInfoCard/ContactInfoCard.tsx, packages/apps/crm/src/components/molecules/SocialNetworksInfoCard/SocialNetworksInfoCard.tsx, packages/apps/crm/src/components/organisms/DropdownAddressesView/DropdownAddressesView.tsx, packages/apps/crm/src/components/organisms/DropdownContactView/DropdownContactView.tsx, packages/apps/crm/src/screens/client/ClientDetailsScreen.js
=> feat: add contact information addition management

changelogs/unreleased/91004.json, packages/apps/quality/src/components/molecules/ControlEntryFormButtons/ControlEntryFormButtons.tsx, packages/apps/quality/src/components/organisms/SampleNotFoundView/SampleNotFoundView.tsx, packages/apps/quality/src/components/organisms/index.ts, packages/apps/quality/src/features/controlEntrySampleLineSlice.js, packages/apps/quality/src/i18n/en.json, packages/apps/quality/src/i18n/fr.json, packages/apps/quality/src/screens/ControlEntryFormScreen.js
=> fix: add null checks to avoid crash on Control entry line

changelogs/unreleased/91002.json, packages/core/src/apiProviders/utils.ts
=> feat: add current request path in the traceback to make it more readable

packages/apps/dms/src/components/atoms/DirectoryCard/DirectoryCard.tsx, packages/apps/dms/src/components/molecules/DocumentActionCard/DocumentActionCard.tsx, packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
=> fix: add access control on dms package

changelogs/unreleased/91564_crm.json, changelogs/unreleased/91564_project.json, packages/apps/crm/src/hooks/use-crm-header-actions.ts, packages/apps/crm/src/models/objectFields.ts, packages/apps/project/src/models/objectFields.ts
=> fix: update address model structure

changelogs/unreleased/91562.json, packages/apps/sale/src/components/atoms/SaleOrderBottomButton/SaleOrderBottomButton.tsx, packages/apps/sale/src/components/molecules/CartHeader/CartHeader.tsx, packages/apps/sale/src/components/molecules/CartLineActionCard/CartLineActionCard.tsx, packages/apps/sale/src/components/molecules/CartLineValidationButton/CartLineValidationButton.tsx, packages/apps/sale/src/components/molecules/CatalogActionCard/CatalogActionCard.tsx, packages/apps/sale/src/hooks/use-sale-header-actions.ts, packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx, packages/apps/sale/src/screens/cart/CartLineDetailsScreen.tsx, packages/apps/sale/src/screens/saleOrder/SaleQuotationCreationScreen.tsx, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json
=> refactor: check permission access on sale package

changelogs/unreleased/91563.json, packages/apps/project/src/components/molecules/TaskActionCard/TaskActionCard.tsx, packages/apps/project/src/components/organisms/CustomSection/CustomSection.tsx, packages/apps/project/src/components/pages/TaskView/TaskView.tsx, packages/apps/project/src/screens/ProjectDetailsScreen.tsx, packages/apps/project/src/screens/TaskDetailsScreen.tsx
=> refactor: check permission access on project package

changelogs/unreleased/91561.json, packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx, packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json
=> refactor: check perm in leave button

changelogs/unreleased/91557.json, packages/apps/hr/src/api/leave-api.js, packages/apps/hr/src/components/molecules/LeaveDetailsButtons/LeaveDetailsButtons.tsx, packages/apps/hr/src/components/templates/LeaveFilters/LeaveFilters.tsx, packages/apps/hr/src/components/templates/LeaveRefusalPopup/LeaveRefusalPopup.tsx, packages/apps/hr/src/components/templates/LeaveWaitingValidationSearchBar/LeaveWaitingValidationSearchBar.tsx, packages/apps/hr/src/features/leaveSlice.js, packages/apps/hr/src/screens/leaveRequests/LeaveFormScreen.tsx, packages/apps/hr/src/screens/leaveRequests/LeaveListScreen.tsx
=> refactor: manage company in leave api

changelogs/unreleased/91555.json, packages/apps/purchase/src/api/purchase-request-api.js, packages/apps/purchase/src/api/supplier-api.js, packages/apps/purchase/src/components/templates/SupplierSearchBar/SupplierSearchBar.tsx, packages/apps/purchase/src/screens/RequestListScreen.tsx
=> refactor: manage company in purchase

changelogs/unreleased/91804.json, packages/apps/crm/src/models/typeObjects.ts
=> fix: manage dynamic selection on crm

changelogs/unreleased/91916.json, packages/core/src/auth/index.ts
=> fix: user fetch for dashboards and webview menus generation

packages/apps/purchase/src/i18n/en.json, packages/apps/purchase/src/i18n/fr.json, packages/apps/purchase/src/screens/RequestCreationScreen.tsx
=> fix: change description title on purchase creation form

changelogs/unreleased/92162.json, packages/core/src/auth/components/molecules/TranslationsButton/TranslationsButton.tsx, packages/core/src/auth/features/configSlice.js, packages/core/src/auth/i18n/en.json, packages/core/src/auth/i18n/fr.json, packages/core/src/i18n/api/translation.js, packages/core/src/i18n/component/Translator.js
=> fix: improve logic on translations upload

packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx, packages/apps/dms/src/screens/MyFavoriteDocumentsScreen.tsx
=> fix: add showClearButton on DMS chipSelect

changelogs/unreleased/92154.json, packages/apps/purchase/src/api/index.ts, packages/apps/purchase/src/api/purchase-request-api.js, packages/apps/purchase/src/features/purchaseRequestSlice.js, packages/apps/purchase/src/i18n/en.json, packages/apps/purchase/src/i18n/fr.json, packages/apps/purchase/src/screens/RequestDetailsScreen.tsx, packages/ui/__tests__/components/molecules/EditableHtmlInput.test.js, packages/ui/src/components/molecules/EditableHtmlInput/EditableHtmlInput.tsx, packages/ui/src/components/molecules/index.tsx, packages/ui/stories/molecules/EditableHtmlInput.stories.tsx
=> feat: enable edit on description on request details screen

changelogs/unreleased/91930.json, packages/core/src/dashboards/menu.helpers.ts, packages/core/src/forms/studio/permission.helpers.ts, packages/core/src/utils/index.ts, packages/core/src/utils/role.ts, packages/core/src/webViews/menu.helper.ts
=> feat: add tool to get all roles of user

package.json, packages/apps/message/.eslintrc.js, packages/apps/message/.prettierrc.js, packages/apps/message/README.md, packages/apps/message/babel.config.js, packages/apps/message/package.json, packages/apps/message/src/i18n/en.json, packages/apps/message/src/i18n/fr.json, packages/apps/message/src/index.ts, packages/apps/message/tsconfig.build.json, packages/apps/message/tsconfig.json, src/App.js
=> feat: create package @axelor/aos-mobile-message

changelogs/unreleased/92548.json, packages/core/src/components/organisms/DateInput/DateInput.tsx
=> fix: date not save on click outside on DateInput

changelogs/unreleased/92549.json, packages/apps/crm/src/screens/event/EventFormScreen.js, packages/apps/crm/src/screens/event/EventPlanningScreen.js
=>  fix: crash when trying to add an event from the planning

changelogs/unreleased/92628.json, packages/apps/crm/src/screens/event/EventFormScreen.js
=> fix: period error when creating an event

changelogs/unreleased/92436_LabelText.json, changelogs/unreleased/92436_LineCard.json, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx, packages/ui/__tests__/components/molecules/LabelText.test.js, packages/ui/src/components/molecules/LabelText/LabelText.tsx
=> fix: display issue line card

changelogs/unreleased/92404.json, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineButtons/CustomerDeliveryLineButtons.js, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineButtons/InternalMoveLineButtons.js, packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineButtons/SupplierArrivalLineButtons.js
=> fix: improve navigation after line validation

packages/core/src/app/ContextsProvider.tsx, packages/core/src/components/organisms/PopupFilters/PopupFilters.tsx, packages/core/src/header/FilterProvider.tsx, packages/core/src/header/hooks.js, packages/core/src/hooks/use-active-filter.ts
=> feat: add AOP filters management

changelogs/unreleased/92881.json, ios/AosMobile.xcodeproj/project.pbxproj, ios/AosMobile/Info.plist
=> fix: add configuration for iPad

packages/core/src/apiProviders/index.js, packages/core/src/auth/index.ts
=> fix: add missing export

docs/doc/en/tools/60_headers.md, docs/doc/fr/tools/60_headers.md, packages/apps/crm/src/hooks/use-crm-header-actions.ts, packages/apps/helpdesk/src/hooks/use-helpdesk-header-actions.ts, packages/apps/hr/src/hooks/use-hr-header-actions.js, packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js, packages/apps/hr/src/screens/timesheet/TimerFormScreen.js, packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js, packages/apps/intervention/src/hooks/use-intervention-header-actions.ts, packages/apps/manufacturing/src/hooks/use-manufacturing-headers.js, packages/apps/project/src/hooks/use-project-header-actions.ts, packages/apps/purchase/src/hooks/use-purchase-header-actions.ts, packages/apps/sale/src/hooks/use-sale-header-actions.ts, packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx, packages/apps/stock/src/hooks/use-stock-header-actions.js
=> feat: remove unused dependencies on header hooks

changelogs/unreleased/92917.json, packages/apps/dms/src/api/document-api.js, packages/apps/dms/src/components/atoms/DocumentCard/DocumentCard.tsx
=> fix: modify dms extension filter management

changelogs/unreleased/92918.json, packages/core/src/tools/FileDownloader.ts
=> fix: remove illegal characters before downloading

changelogs/unreleased/92478.json, packages/apps/crm/src/api/catalog-api.js, packages/apps/crm/src/api/client-api.js, packages/apps/crm/src/api/contact-api.js, packages/apps/crm/src/api/leads-api.js, packages/apps/crm/src/api/opportunities-api.js, packages/apps/crm/src/api/prospect-api.js, packages/apps/crm/src/api/tour-api.js, packages/apps/crm/src/hooks/use-crm-header-actions.ts, packages/apps/crm/src/screens/client/index.js, packages/apps/crm/src/screens/contact/index.js, packages/apps/crm/src/screens/prospect/index.js, packages/apps/crm/src/screens/tour/index.js, packages/core/src/api/aop-filter-api.ts, packages/core/src/apiProviders/Standard/requests.helper.ts, packages/core/src/header/FilterProvider.tsx, packages/core/src/header/hooks.tsx, packages/core/src/models/objectFields.ts
=> refactor: use AOP filter on CRM list views

changelogs/unreleased/93663.json, packages/core/src/components/external/Scanner/Scanner.tsx
=> fix: correctly create datawedge profile

changelogs/unreleased/93320.json, changelogs/unreleased/93320_config.json, changelogs/unreleased/93320_websocket.json, docs/doc/en/tools/110_websocket.md, docs/doc/fr/tools/110_websocket.md, packages/core/src/app/Application.tsx, packages/core/src/app/ContextsProvider.tsx, packages/core/src/features/authSlice.js, packages/core/src/index.ts, packages/core/src/websocket/WebSocketProvider.tsx, packages/core/src/websocket/hooks.ts, packages/core/src/websocket/index.ts, packages/core/src/websocket/types.ts, src/app.config.js
=> feat: add WebSocket support

packages/apps/message/src/api/index.ts, packages/apps/message/src/api/mail-message-api.ts, packages/apps/message/src/components/atoms/ReadIcon/ReadIcon.tsx, packages/apps/message/src/components/molecules/CommentCard/CommentCard.tsx, packages/apps/message/src/components/molecules/NotificationCard/NotificationCard.tsx, packages/apps/message/src/components/organisms/MailMessageCard/MailMessageCard.tsx, packages/apps/message/src/components/templates/MailMessageView/MailMessageView.tsx, packages/apps/message/src/features/asyncFunctions-index.ts, packages/apps/message/src/features/mailMessageSlice.js, packages/apps/message/src/hooks/use-message-header-actions.tsx, packages/apps/message/src/i18n/en.json, packages/apps/message/src/i18n/fr.json, packages/apps/message/src/screens/InboxScreen.tsx, packages/apps/message/src/screens/index.ts, packages/apps/project/src/components/molecules/ActivityCard/ActivityCard.tsx
=> feat: add messenger header action on user screen

packages/apps/message/src/hooks/use-message-header-actions.tsx
=> feat: improve header action with unread messages count

changelogs/unreleased/92480.json, packages/apps/helpdesk/src/api/ticket-api.js, packages/apps/helpdesk/src/hooks/use-helpdesk-header-actions.ts, packages/apps/helpdesk/src/screens/index.js
=> refactor: use AOP filter on Helpedsk list views

changelogs/unreleased/92486.json, packages/apps/purchase/src/api/purchase-request-api.js, packages/apps/purchase/src/hooks/use-purchase-header-actions.ts, packages/apps/purchase/src/screens/index.ts
=> refactor: use AOP filter on Purchase list views

changelogs/unreleased/92488.json, packages/apps/sale/src/api/customer-api.js, packages/apps/sale/src/api/product-api.js, packages/apps/sale/src/api/sale-order-api.js, packages/apps/sale/src/hooks/use-sale-header-actions.ts, packages/apps/sale/src/screens/cart/index.ts, packages/apps/sale/src/screens/client/index.ts, packages/apps/sale/src/screens/product/index.ts, packages/apps/sale/src/screens/saleOrder/index.ts
=> refactor: use AOP filter on Sale list Views

changelogs/unreleased/92483.json, packages/apps/manufacturing/src/api/manufacturing-order-api.js, packages/apps/manufacturing/src/api/operation-order-api.js, packages/apps/manufacturing/src/hooks/use-manufacturing-headers.js, packages/apps/manufacturing/src/screens/manufactoringOrder/index.js, packages/apps/manufacturing/src/screens/operationOrder/index.js
=> refactor: use AOP filter on Manufacturing list views

changelogs/unreleased/92485.json, packages/apps/project/src/api/project-api.js, packages/apps/project/src/api/project-task-api.js, packages/apps/project/src/hooks/use-project-header-actions.ts, packages/apps/project/src/screens/index.ts
=> refactor: use AOPfilter on Project list views

packages/apps/message/src/hooks/use-message-header-actions.tsx
=> feat: add config management for inbox access

changelogs/unreleased/93015.json, packages/core/src/api/currency-api.ts, packages/core/src/api/index.ts, packages/core/src/features/asyncFunctions-index.ts, packages/core/src/features/currencySlice.ts, packages/core/src/features/index.js, packages/core/src/hooks/use-currency-formatter.ts, packages/core/src/i18n/translations/en.json, packages/core/src/i18n/translations/fr.json, packages/core/src/models/objectFields.ts, packages/core/src/navigator/Navigator.js
=> feat: add currency formatting management

changelogs/unreleased/93017.json, packages/apps/sale/src/components/atoms/SaleOrderCard/SaleOrderCard.tsx, packages/apps/sale/src/components/atoms/SaleOrderLineCard/SaleOrderLineCard.tsx, packages/apps/sale/src/components/molecules/SaleOrderLinePriceDetails/SaleOrderLinePriceDetails.tsx, packages/apps/sale/src/components/molecules/SaleOrderPriceDetails/SaleOrderPriceDetails.tsx, packages/apps/sale/src/components/organisms/DropDownSaleOrderView/DropDownSaleOrderView.tsx, packages/apps/sale/src/components/pages/SaleOrderListView/SaleOrderListView.tsx, packages/apps/sale/src/screens/saleOrder/SaleOrderLineListScreen.tsx
=> refactor: use new tool to format totals with currency in sale

changelogs/unreleased/93996.json, packages/core/src/api/metafile-api.ts, packages/core/src/tools/FileDownloader.ts, packages/core/src/utils/file.ts, packages/core/src/utils/index.ts
=> fix: remove illegal characters from filename before uploading

packages/core/src/utils/file.ts
=> fix: can't upload file with accents in name

changelogs/unreleased/94447.json, packages/apps/manufacturing/src/features/prodProductSlice.js
=> fix: use the correct product Api import

changelogs/unreleased/94849.json, packages/apps/intervention/src/components/organisms/DropdownCards/DropdownCards.tsx
=> fix: resolve null issue on intervention contact

changelogs/unreleased/94850.json, packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js
=> fix: remove duplicated screen name on inventory line navigation

packages/apps/message/src/api/index.ts, packages/apps/message/src/api/mail-message-api.ts, packages/apps/message/src/components/atoms/Avatar/Avatar.tsx, packages/apps/message/src/components/atoms/ReadIcon/ReadIcon.tsx, packages/apps/message/src/components/atoms/index.ts, packages/apps/message/src/components/molecules/CommentCard/CommentCard.tsx, packages/apps/message/src/components/molecules/NotificationCard/NotificationCard.tsx, packages/apps/message/src/components/organisms/MailMessageCard/MailMessageCard.tsx, packages/apps/message/src/screens/InboxScreen.tsx
=> feat: add responses management

changelogs/unreleased/96018.json, changelogs/unreleased/96018_badges.json, changelogs/unreleased/96018_date.json, packages/apps/stock/src/components/atoms/OrderQtyIndicatorCard/OrderQtyIndicatorCard.tsx, packages/apps/stock/src/i18n/en.json, packages/apps/stock/src/i18n/fr.json, packages/apps/stock/src/models/objectFields.ts
=> refactor: improve sale & purchase order qty indicator card

changelogs/unreleased/96016.json, packages/apps/stock/src/models/searchFields.ts
=> refactor: improve search fields on stock move

changelogs/unreleased/95900.json, packages/apps/stock/src/models/objectFields.ts, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectProductScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectTrackingScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveSelectProductScreen.js, packages/apps/stock/src/screens/internalMoves/InternalMoveSelectTrackingScreen.js, packages/apps/stock/src/screens/inventories/InventorySelectProductScreen.js, packages/apps/stock/src/screens/inventories/InventorySelectTrackingScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectProductScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectTrackingScreen.js, packages/apps/stock/src/utils/line-navigation.ts
=> fix: add missing information on line verification

changelogs/unreleased/95510.json, packages/apps/message/src/components/atoms/AuthorText/AuthorText.tsx, packages/apps/message/src/components/atoms/index.ts, packages/apps/message/src/components/organisms/MailMessageCard/MailMessageCard.tsx, packages/core/src/utils/date.ts, packages/core/src/utils/index.ts
=> refactor: display time instead of date time information

changelogs/unreleased/96989.json, changelogs/unreleased/96989_error-message.json, packages/apps/stock/src/components/organisms/SearchLineContainer/SearchLineContainer.tsx, packages/ui/__tests__/components/organisms/AutoCompleteSearch.test.js, packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
=> fix: avoid selecting wrong product when scanning a line

changelogs/unreleased/97314.json, packages/apps/sale/src/api/product-api.js, packages/apps/sale/src/components/molecules/CatalogActionCard/CatalogActionCard.tsx
=> fix: resolve issue on variant selection popup

packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderDetailsScreen.js, packages/apps/manufacturing/src/screens/operationOrder/OperationOrderDetailsScreen.js, packages/apps/quality/src/api/index.ts, packages/apps/quality/src/api/manuf-order-api.js, packages/apps/quality/src/api/operation-order-api.js, packages/apps/quality/src/api/purchase-order-api.js, packages/apps/quality/src/api/qi-detection-api.js, packages/apps/quality/src/api/sale-order-api.js, packages/apps/quality/src/api/stock-move-api.js, packages/apps/quality/src/components/templates/CustomerOrderSearchBar/CustomerOrderSearchBar.tsx, packages/apps/quality/src/components/templates/QIDetectionSearchBar/QIDetectionSearchBar.tsx, packages/apps/quality/src/components/templates/SupplierOrderSearchBar/SupplierOrderSearchBar.tsx, packages/apps/quality/src/features/asyncFunctions-index.ts, packages/apps/quality/src/features/index.js, packages/apps/quality/src/features/manufOrderSlice.js, packages/apps/quality/src/features/operationOrderSlice.js, packages/apps/quality/src/features/stockMoveSlice.js, packages/apps/quality/src/i18n/en.json, packages/apps/quality/src/i18n/fr.json, packages/apps/quality/src/index.ts, packages/apps/quality/src/models/forms.ts, packages/apps/quality/src/models/objectFields.ts, packages/apps/quality/src/screens/QualityImprovement/QualityImprovementFormScreen.tsx, packages/apps/stock/src/index.ts, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryDetailScreen.js, packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalDetailsScreen.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
=> feat: add quick access to QI creation

packages/apps/quality/src/api/index.ts, packages/apps/quality/src/api/quality-improvement-api.js, packages/apps/quality/src/components/molecules/QIFormButton/QIFormButton.tsx, packages/apps/quality/src/components/templates/DefectViewAllList/DefectViewAllList.tsx, packages/apps/quality/src/features/asyncFunctions-index.ts, packages/apps/quality/src/features/qualityImprovementSlice.js, packages/apps/quality/src/i18n/en.json, packages/apps/quality/src/i18n/fr.json, packages/apps/quality/src/screens/QualityImprovement/QualityImprovementFormScreen.tsx
=> feat: use request to create/update a QI

packages/ui/__tests__/components/atoms/Input.test.js
=> refactor: use rntl test for Input component

packages/ui/__tests__/components/atoms/Icon.test.js, packages/ui/src/components/atoms/Icon/Icon.tsx
=> refactor: use rntl for Icon component

changelogs/release/97544.json, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineNotes/InternalMoveLineNotes.js, packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
=> fix: resolve issue on InternalMove notes from line details

packages/ui/__tests__/components/atoms/Switch.test.js, packages/ui/src/components/atoms/Switch/Switch.tsx
=> refactor: use rntl test for Switch component

changelogs/unreleased/98006.json, packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
=> fix: add click outside management on HtmlInput

packages/apps/project/src/api/check-list-api.ts, packages/apps/project/src/api/index.ts, packages/apps/project/src/components/atoms/CheckListItemCard/CheckListItemCard.tsx, packages/apps/project/src/components/atoms/ParentCheckListItemCard/ParentCheckListItemCard.tsx, packages/apps/project/src/components/atoms/index.ts, packages/apps/project/src/components/molecules/CheckListItemActionCard/CheckListItemActionCard.tsx, packages/apps/project/src/components/molecules/index.ts, packages/apps/project/src/components/templates/CheckListView/CheckListView.tsx, packages/apps/project/src/components/templates/index.ts, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/checkListSlice.js, packages/apps/project/src/features/index.js, packages/apps/project/src/hooks/index.ts, packages/apps/project/src/hooks/use-check-list-item-actions.ts, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json, packages/apps/project/src/models/objectFields.ts, packages/apps/project/src/models/searchFields.ts, packages/apps/project/src/models/sortFields.ts, packages/apps/project/src/types/check-list-item-status.ts, packages/apps/project/src/types/index.ts
=> feat: add CheckListView component

changelogs/unreleased/97720.json, changelogs/unreleased/97720_objectCard.json, packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx, packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx, packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx, packages/ui/__tests__/components/atoms/BootstrapIcon.test.js, packages/ui/__tests__/components/atoms/Icon.test.js, packages/ui/__tests__/components/molecules/Button.test.js, packages/ui/__tests__/components/templates/ObjectCard.test.js, packages/ui/src/components/atoms/BootstrapIcon/BootstrapIcon.tsx, packages/ui/src/components/molecules/Image/Image.tsx, packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx
=> refactor: improve StockMoveLine cards display

changelogs/unreleased/97551_machine.json, packages/apps/maintenance/package.json, packages/apps/maintenance/src/api/index.ts, packages/apps/maintenance/src/api/maintenance-request-api.ts, packages/apps/maintenance/src/components/atoms/MaintenanceRequestCard/MaintenanceRequestCard.tsx, packages/apps/maintenance/src/components/atoms/index.ts, packages/apps/maintenance/src/components/index.ts, packages/apps/maintenance/src/components/molecules/ActionTypePicker/ActionTypePicker.tsx, packages/apps/maintenance/src/components/molecules/index.ts, packages/apps/maintenance/src/components/organisms/MaintenanceRequestFilters/MaintenanceRequestFilters.tsx, packages/apps/maintenance/src/components/organisms/index.ts, packages/apps/maintenance/src/features/asyncFunctions-index.ts, packages/apps/maintenance/src/features/index.ts, packages/apps/maintenance/src/features/maintenanceRequestSlice.js, packages/apps/maintenance/src/hooks/use-maintenance-header-actions.ts, packages/apps/maintenance/src/i18n/en.json, packages/apps/maintenance/src/i18n/fr.json, packages/apps/maintenance/src/index.ts, packages/apps/maintenance/src/models/index.ts, packages/apps/maintenance/src/models/objectFields.ts, packages/apps/maintenance/src/models/searchFields.ts, packages/apps/maintenance/src/models/sortFields.ts, packages/apps/maintenance/src/models/typeObjects.ts, packages/apps/maintenance/src/screens/MaintenanceRequestListScreen.tsx, packages/apps/maintenance/src/screens/index.ts, packages/apps/manufacturing/src/components/templates/MachineSearchBar/MachineSearchBar.tsx
=> feat: add maintenance request list screen

changelogs/unreleased/97552_navigation.json, changelogs/unreleased/97552_radioSelect.json, packages/apps/maintenance/src/api/equipement-maintenance-api.ts, packages/apps/maintenance/src/api/index.ts, packages/apps/maintenance/src/api/maintenance-request-api.ts, packages/apps/maintenance/src/components/atoms/EquipementMaintenanceCard/EquipementMaintenanceCard.tsx, packages/apps/maintenance/src/components/atoms/index.ts, packages/apps/maintenance/src/components/molecules/ActionRadioSelect/ActionRadioSelect.tsx, packages/apps/maintenance/src/components/molecules/EquipementMaintenanceActionCard/EquipementMaintenanceActionCard.tsx, packages/apps/maintenance/src/components/molecules/index.ts, packages/apps/maintenance/src/components/organisms/EquipementMaintenanceSearchBar/EquipementMaintenanceSearchBar.tsx, packages/apps/maintenance/src/components/organisms/index.ts, packages/apps/maintenance/src/features/asyncFunctions-index.ts, packages/apps/maintenance/src/features/equipementMaintenanceSlice.ts, packages/apps/maintenance/src/features/index.ts, packages/apps/maintenance/src/features/maintenanceRequestSlice.ts, packages/apps/maintenance/src/i18n/en.json, packages/apps/maintenance/src/i18n/fr.json, packages/apps/maintenance/src/index.ts, packages/apps/maintenance/src/models/forms.ts, packages/apps/maintenance/src/models/index.ts, packages/apps/maintenance/src/models/objectFields.ts, packages/apps/maintenance/src/models/searchFields.ts, packages/apps/maintenance/src/models/sortFields.ts, packages/apps/maintenance/src/screens/MaintenanceRequestFormScreen.tsx, packages/apps/maintenance/src/screens/index.ts, packages/core/src/hooks/index.ts, packages/core/src/hooks/use-navigation.ts, packages/ui/__tests__/components/molecules/RadioSelect.test.js, packages/ui/src/components/molecules/RadioSelect/RadioSelect.tsx
=> feat: add maintenance request form view

changelogs/unreleased/97411.json, packages/apps/quality/src/api/index.ts, packages/apps/quality/src/api/qi-detection-api.js, packages/apps/quality/src/features/asyncFunctions-index.ts, packages/apps/quality/src/features/qiDetectionSlice.js, packages/apps/quality/src/i18n/en.json, packages/apps/quality/src/i18n/fr.json, packages/apps/quality/src/models/objectFields.ts, packages/apps/quality/src/screens/QualityImprovement/QualityImprovementFormScreen.tsx
=> feat: add management of default qiDetection value

changelogs/unreleased/97179.json, changelogs/unreleased/97179_periodInput.json, packages/apps/crm/src/components/organisms/EventPeriodInput/EventPeriodInput.tsx, packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
=> refactor: improve date display on event form

changelogs/unreleased/97321.json, changelogs/unreleased/97321_cardProduct.json, changelogs/unreleased/97321_priceListCard.json, packages/apps/sale/src/components/atoms/PriceDetails/PriceDetails.tsx, packages/apps/sale/src/components/atoms/ProductCard/ProductCard.tsx, packages/apps/sale/src/components/atoms/SaleOrderLineCard/SaleOrderLineCard.tsx, packages/apps/sale/src/components/molecules/SaleOrderLineAvailabilityBadges/SaleOrderLineAvailabilityBadges.tsx, packages/apps/sale/src/components/molecules/SaleOrderLinePriceDetails/SaleOrderLinePriceDetails.tsx, packages/apps/sale/src/components/molecules/index.ts, packages/apps/sale/src/hooks/index.ts, packages/apps/sale/src/hooks/use-sale-order-line-availability.ts, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/index.ts, packages/apps/sale/src/models/objectFields.ts, packages/apps/sale/src/models/typeObjects.ts, packages/apps/sale/src/screens/saleOrder/SaleOrderLineDetailsScreen.tsx, packages/apps/sale/src/screens/saleOrder/SaleOrderLineListScreen.tsx
=> feat: add disponibility display on SaleOrderLine

changelogs/unreleased/98571.json, changelogs/unreleased/98571_cameraKey.json, packages/core/src/features/cameraScannerSlice.ts, packages/core/src/utils/formatters.ts
=> fix: resolve key and format issues with camera scanner

changelogs/unreleased/98824.json, packages/ui/__tests__/components/molecules/Increment.test.js, packages/ui/src/components/molecules/Increment/Increment.tsx, packages/ui/src/utils/formatters.ts
=> fix: improve formatting on increment input

packages/apps/project/src/api/check-list-api.ts, packages/apps/project/src/components/molecules/CheckListItemActionCard/CheckListItemActionCard.tsx, packages/apps/project/src/components/templates/CheckListView/CheckListView.tsx, packages/apps/project/src/hooks/use-check-list-item-actions.ts
=> feat: add api action on checklist item update

changelogs/unreleased/97316_modules.json, changelogs/unreleased/97316_theme.json, changelogs/unreleased/97316_translation.json, packages/apps/sale/src/components/organisms/SaleQuotationCreationButtons/SaleQuotationCreationButtons.tsx, packages/apps/sale/src/hooks/use-sale-header-actions.tsx, packages/apps/sale/src/screens/saleOrder/SaleQuotationCreationScreen.tsx, packages/core/src/app/modules/ModuleProvider.ts, packages/core/src/auth/i18n/fr.json, packages/ui/src/theme/color/content.helpers.ts
=> feat: add sale quotation creation from customer details view

changelogs/unreleased/97178.json, packages/apps/sale/src/hooks/use-sale-header-actions.tsx, packages/apps/sale/src/screens/client/ClientSaleDetailsScreen.tsx
=> feat: add create event on sale client details view

changelogs/unreleased/84325.json, packages/apps/crm/src/screens/client/ClientFormScreen.tsx, packages/apps/sale/src/components/molecules/ValidateCartPopup/ValidateCartPopup.tsx, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/screens/client/ClientSaleFormScreen.tsx
=> feat: add possibility to create a client on cart validation

changelogs/unreleased/97181.json, changelogs/unreleased/97181_refactor-header.json, changelogs/unreleased/97181_selection.json, packages/apps/crm/src/components/atoms/EventStatusMultiPicker/EventStatusMultiPicker.tsx, packages/apps/crm/src/components/atoms/index.ts, packages/apps/crm/src/components/organisms/Event/EventHeader/EventHeader.js, packages/apps/crm/src/components/organisms/EventPlanningFilters/EventPlanningFilters.tsx, packages/apps/crm/src/components/organisms/index.js, packages/apps/crm/src/models/typeObjects.ts, packages/apps/crm/src/screens/event/EventPlanningScreen.tsx
=> feat: add status filter on event planning view

changelogs/unreleased/97322.json, changelogs/unreleased/97322_fix.json, packages/apps/sale/src/api/alternative-barcode-api.js, packages/apps/sale/src/api/index.ts, packages/apps/sale/src/api/product-api.js, packages/apps/sale/src/components/organisms/ProductSearchBar/ProductSearchBar.tsx, packages/apps/sale/src/features/alternativeBarcodeSlice.js, packages/apps/sale/src/features/asyncFunctions-index.ts, packages/apps/sale/src/features/index.js, packages/apps/sale/src/i18n/en.json, packages/apps/sale/src/i18n/fr.json, packages/apps/sale/src/models/objectFields.ts, packages/apps/sale/src/models/searchFields.ts, packages/apps/sale/src/screens/cart/CartLineDetailsScreen.tsx, packages/apps/sale/src/screens/product/ProductSaleListScreen.tsx, packages/apps/sale/src/screens/saleOrder/SaleQuotationCreationScreen.tsx, packages/core/src/components/templates/DoubleScannerSearchBar/DoubleScannerSearchBar.tsx
=> feat: add doubleScannerSearchBar on ProductSaleListScreen

packages/apps/project/src/api/check-list-api.ts, packages/apps/project/src/api/index.ts, packages/apps/project/src/features/asyncFunctions-index.ts, packages/apps/project/src/features/checkListSlice.js, packages/apps/project/src/hooks/use-check-list-item-actions.ts, packages/apps/project/src/i18n/en.json, packages/apps/project/src/i18n/fr.json
=> feat: add checklist item deletion management

changelogs/unreleased/101272.json, packages/apps/stock/src/features/trackingNumberSlice.js, packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalAddTrackingScreen.js
=> fix: adapt tracking number creation to stay reusable and refresh supplier line details

packages/apps/stock/src/models/forms.ts, packages/apps/stock/src/models/objectFields.ts
=> fix: rename logistical form multi clients config
